import { defineConfig } from "oxfmt";

export const oxFmtConfig = defineConfig({
  printWidth: 100,
  tabWidth: 2,
  useTabs: false,
  semi: true,
  singleQuote: false,
  trailingComma: "all",
  jsxSingleQuote: false,
  quoteProps: "as-needed",
  arrowParens: "always",
  bracketSpacing: true,
  bracketSameLine: false,
  endOfLine: "lf",
  embeddedLanguageFormatting: "auto",
  objectWrap: "preserve",
  proseWrap: "preserve",
  htmlWhitespaceSensitivity: "css",
  insertFinalNewline: true,
  sortImports: {
    order: "asc",
    ignoreCase: true,
    sortSideEffects: false,
    partitionByNewline: true,
    partitionByComment: true,
    newlinesBetween: false,
    internalPattern: ["~/", "@/", "@namera-ai/"],
    customGroups: [
      {
        groupName: "framework",
        elementNamePattern: ["react", "react/*", "react-dom", "react-dom/*", "next", "next/*"],
      },
      {
        groupName: "tanstack",
        elementNamePattern: ["@tanstack/*"],
      },
    ],
    groups: [
      "type-builtin",
      "type-external",
      ["type-internal", "type-subpath"],
      "builtin",
      "framework",
      "tanstack",
      "external",
      ["internal", "subpath"],
      ["parent", "sibling", "index"],
      "style",
      "unknown",
    ],
  },
  sortTailwindcss: {
    functions: ["clsx", "cn", "cva", "twMerge", "tw"],
    attributes: ["class", "className"],
    preserveWhitespace: false,
    preserveDuplicates: false,
  },
  sortPackageJson: {
    sortScripts: true,
  },
  ignorePatterns: [
    "**/node_modules/**",
    "**/dist/**",
    "**/build/**",
    "**/.turbo/**",
    "**/.next/**",
    "**/.output/**",
    "**/coverage/**",
    "**/storybook-static/**",
  ],
});
