CREATE POLICY "account_select" ON "auth"."account" AS PERMISSIVE FOR SELECT TO "app_user" USING (auth_current_user_id() = "auth"."account"."user_id");--> statement-breakpoint
CREATE POLICY "account_update" ON "auth"."account" AS PERMISSIVE FOR UPDATE TO "app_user" USING (auth_current_user_id() = "auth"."account"."user_id") WITH CHECK (auth_current_user_id() = "auth"."account"."user_id");--> statement-breakpoint
CREATE POLICY "account_insert" ON "auth"."account" AS PERMISSIVE FOR INSERT TO "app_user" WITH CHECK (auth_current_user_id() = "auth"."account"."user_id");--> statement-breakpoint
CREATE POLICY "account_admin_access" ON "auth"."account" AS PERMISSIVE FOR ALL TO "app_admin" USING (true);--> statement-breakpoint
CREATE POLICY "session_select" ON "auth"."session" AS PERMISSIVE FOR SELECT TO "app_user" USING (auth_current_user_id() = "auth"."session"."user_id");--> statement-breakpoint
CREATE POLICY "session_update" ON "auth"."session" AS PERMISSIVE FOR UPDATE TO "app_user" USING (auth_current_user_id() = "auth"."session"."user_id") WITH CHECK ((auth_current_user_id() = "auth"."session"."user_id") AND (("auth"."session"."active_organization_id" IS NULL) OR (auth_user_has_org_access("auth"."session"."active_organization_id"))));--> statement-breakpoint
CREATE POLICY "session_access" ON "auth"."session" AS PERMISSIVE FOR ALL TO "app_admin" USING (true);--> statement-breakpoint
CREATE POLICY "user_select" ON "auth"."user" AS PERMISSIVE FOR SELECT TO "app_user" USING (auth_current_user_id() = "auth"."user"."id");--> statement-breakpoint
CREATE POLICY "user_update" ON "auth"."user" AS PERMISSIVE FOR UPDATE TO "app_user" USING (auth_current_user_id() = "auth"."user"."id") WITH CHECK (auth_current_user_id() = "auth"."user"."id");--> statement-breakpoint
CREATE POLICY "user_adminaccess" ON "auth"."user" AS PERMISSIVE FOR ALL TO "app_admin" USING (true);--> statement-breakpoint
CREATE POLICY "verification_admin_access" ON "auth"."verification" AS PERMISSIVE FOR ALL TO "app_admin" USING (true);--> statement-breakpoint
CREATE POLICY "organization_select" ON "auth"."organization" AS PERMISSIVE FOR SELECT TO "app_user" USING (auth_user_has_permissions_in_org("auth"."organization"."id", ARRAY['org:read']::text[]));--> statement-breakpoint
CREATE POLICY "organization_update" ON "auth"."organization" AS PERMISSIVE FOR UPDATE TO "app_user" USING (auth_user_has_permissions_in_org("auth"."organization"."id", ARRAY['org:update']::text[])) WITH CHECK (auth_user_has_permissions_in_org("auth"."organization"."id", ARRAY['org:update']::text[]));--> statement-breakpoint
CREATE POLICY "organization_admin_access" ON "auth"."organization" AS PERMISSIVE FOR ALL TO "app_admin" USING (true);--> statement-breakpoint
CREATE POLICY "member_select" ON "auth"."member" AS PERMISSIVE FOR SELECT TO "app_user" USING (auth_user_has_permissions_in_org("auth"."member"."organization_id", ARRAY['member:read']::text[]));--> statement-breakpoint
CREATE POLICY "member_insert" ON "auth"."member" AS PERMISSIVE FOR INSERT TO "app_user" WITH CHECK (auth_user_has_permissions_in_org("auth"."member"."organization_id", ARRAY['member:invite']::text[]));--> statement-breakpoint
CREATE POLICY "member_update" ON "auth"."member" AS PERMISSIVE FOR UPDATE TO "app_user" USING (auth_user_has_permissions_in_org("auth"."member"."organization_id", ARRAY['member:update']::text[])) WITH CHECK (auth_user_has_permissions_in_org("auth"."member"."organization_id", ARRAY['member:update']::text[]));--> statement-breakpoint
CREATE POLICY "member_admin_access" ON "auth"."member" AS PERMISSIVE FOR ALL TO "app_admin" USING (true);--> statement-breakpoint
CREATE POLICY "invitation_select" ON "auth"."invitation" AS PERMISSIVE FOR SELECT TO "app_user" USING (auth_user_has_permissions_in_org("auth"."invitation"."organization_id", ARRAY['invitation:read']::text[]));--> statement-breakpoint
CREATE POLICY "invitation_insert" ON "auth"."invitation" AS PERMISSIVE FOR INSERT TO "app_user" WITH CHECK (auth_user_has_permissions_in_org("auth"."invitation"."organization_id", ARRAY['invitation:create']::text[]));--> statement-breakpoint
CREATE POLICY "invitation_update" ON "auth"."invitation" AS PERMISSIVE FOR UPDATE TO "app_user" USING (auth_user_has_permissions_in_org("auth"."invitation"."organization_id", ARRAY['invitation:update']::text[])) WITH CHECK (auth_user_has_permissions_in_org("auth"."invitation"."organization_id", ARRAY['invitation:update']::text[]));--> statement-breakpoint
CREATE POLICY "invitation_admin_access" ON "auth"."invitation" AS PERMISSIVE FOR ALL TO "app_admin" USING (true);--> statement-breakpoint
CREATE POLICY "role_select" ON "auth"."role" AS PERMISSIVE FOR SELECT TO "app_user" USING (auth_user_has_permissions_in_org("auth"."role"."organization_id", ARRAY['role:read']::text[]));--> statement-breakpoint
CREATE POLICY "role_update" ON "auth"."role" AS PERMISSIVE FOR UPDATE TO "app_user" USING (auth_user_has_permissions_in_org("auth"."role"."organization_id", ARRAY['role:update']::text[])) WITH CHECK (auth_user_has_permissions_in_org("auth"."role"."organization_id", ARRAY['role:update']::text[]));--> statement-breakpoint
CREATE POLICY "role_insert" ON "auth"."role" AS PERMISSIVE FOR INSERT TO "app_user" WITH CHECK (auth_user_has_permissions_in_org("auth"."role"."organization_id", ARRAY['role:create']::text[]));--> statement-breakpoint
CREATE POLICY "role_admin_access" ON "auth"."role" AS PERMISSIVE FOR ALL TO "app_admin" USING (true);--> statement-breakpoint
CREATE POLICY "smart_account_select" ON "smart_account" AS PERMISSIVE FOR SELECT TO "app_user" USING (auth_user_has_permissions_in_org("smart_account"."organization_id", ARRAY['smart_account:read']::text[]));--> statement-breakpoint
CREATE POLICY "smart_account_insert" ON "smart_account" AS PERMISSIVE FOR INSERT TO "app_user" WITH CHECK ((auth_current_user_id() = "smart_account"."creator_id") AND (auth_user_has_permissions_in_org("smart_account"."organization_id", ARRAY['smart_account:create']::text[])));--> statement-breakpoint
CREATE POLICY "smart_account_owner_update" ON "smart_account" AS PERMISSIVE FOR UPDATE TO "app_user" USING (auth_user_has_permissions_in_org("smart_account"."organization_id", ARRAY['smart_account:update']::text[])) WITH CHECK (auth_user_has_permissions_in_org("smart_account"."organization_id", ARRAY['smart_account:update']::text[]));--> statement-breakpoint
CREATE POLICY "smart_account_admin_access" ON "smart_account" AS PERMISSIVE FOR ALL TO "app_admin" USING (true);--> statement-breakpoint
CREATE POLICY "session_key_select" ON "session_key" AS PERMISSIVE FOR SELECT TO "app_user" USING (auth_user_has_permissions_in_org("session_key"."organization_id", ARRAY['session_key:read']::text[]));--> statement-breakpoint
CREATE POLICY "session_key_update" ON "session_key" AS PERMISSIVE FOR UPDATE TO "app_user" USING ((auth_user_has_permissions_in_org("session_key"."organization_id", ARRAY['session_key:update']::text[])) AND (auth_session_key_in_org("session_key"."id", "session_key"."organization_id"))) WITH CHECK ((auth_user_has_permissions_in_org("session_key"."organization_id", ARRAY['session_key:update']::text[])) AND (auth_smart_account_in_org("session_key"."smart_account_id", "session_key"."organization_id")));--> statement-breakpoint
CREATE POLICY "session_key_insert" ON "session_key" AS PERMISSIVE FOR INSERT TO "app_user" WITH CHECK ((auth_current_user_id() = "session_key"."creator_id") AND (auth_user_has_permissions_in_org("session_key"."organization_id", ARRAY['session_key:create']::text[])) AND (auth_smart_account_in_org("session_key"."smart_account_id", "session_key"."organization_id")));--> statement-breakpoint
CREATE POLICY "session_key_admin_access" ON "session_key" AS PERMISSIVE FOR ALL TO "app_admin" USING (true);