/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteRouteImport } from './routes/_authed/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AuthedUsersRouteImport } from './routes/_authed/users'
import { Route as AuthedWaitlistRouteImport } from './routes/_authed/waitlist'
import { Route as AuthedInvitesIndexRouteImport } from './routes/_authed/invites/index'
import { Route as AuthedInvitesNewRouteImport } from './routes/_authed/invites/new'

const AuthedRouteRoute = AuthedRouteRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedUsersRoute = AuthedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedWaitlistRoute = AuthedWaitlistRouteImport.update({
  id: '/waitlist',
  path: '/waitlist',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedInvitesIndexRoute = AuthedInvitesIndexRouteImport.update({
  id: '/invites/',
  path: '/invites/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedInvitesNewRoute = AuthedInvitesNewRouteImport.update({
  id: '/invites/new',
  path: '/invites/new',
  getParentRoute: () => AuthedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/login': typeof LoginRoute
  '/users': typeof AuthedUsersRoute
  '/waitlist': typeof AuthedWaitlistRoute
  '/invites/new': typeof AuthedInvitesNewRoute
  '/invites/': typeof AuthedInvitesIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/users': typeof AuthedUsersRoute
  '/waitlist': typeof AuthedWaitlistRoute
  '/': typeof AuthedIndexRoute
  '/invites/new': typeof AuthedInvitesNewRoute
  '/invites': typeof AuthedInvitesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_authed/users': typeof AuthedUsersRoute
  '/_authed/waitlist': typeof AuthedWaitlistRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/invites/new': typeof AuthedInvitesNewRoute
  '/_authed/invites/': typeof AuthedInvitesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/login' | '/users' | '/waitlist' | '/invites/new' | '/invites/'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/users' | '/waitlist' | '/' | '/invites/new' | '/invites'
  id:
    | '__root__'
    | '/_authed'
    | '/login'
    | '/_authed/users'
    | '/_authed/waitlist'
    | '/_authed/'
    | '/_authed/invites/new'
    | '/_authed/invites/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRouteRoute: typeof AuthedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/users': {
      id: '/_authed/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthedUsersRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/waitlist': {
      id: '/_authed/waitlist'
      path: '/waitlist'
      fullPath: '/waitlist'
      preLoaderRoute: typeof AuthedWaitlistRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/invites/': {
      id: '/_authed/invites/'
      path: '/invites'
      fullPath: '/invites/'
      preLoaderRoute: typeof AuthedInvitesIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/invites/new': {
      id: '/_authed/invites/new'
      path: '/invites/new'
      fullPath: '/invites/new'
      preLoaderRoute: typeof AuthedInvitesNewRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
  }
}

interface AuthedRouteRouteChildren {
  AuthedUsersRoute: typeof AuthedUsersRoute
  AuthedWaitlistRoute: typeof AuthedWaitlistRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedInvitesNewRoute: typeof AuthedInvitesNewRoute
  AuthedInvitesIndexRoute: typeof AuthedInvitesIndexRoute
}

const AuthedRouteRouteChildren: AuthedRouteRouteChildren = {
  AuthedUsersRoute: AuthedUsersRoute,
  AuthedWaitlistRoute: AuthedWaitlistRoute,
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedInvitesNewRoute: AuthedInvitesNewRoute,
  AuthedInvitesIndexRoute: AuthedInvitesIndexRoute,
}

const AuthedRouteRouteWithChildren = AuthedRouteRoute._addFileChildren(
  AuthedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthedRouteRoute: AuthedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
