name: namera-telemetry

services:
  lgtm:
    image: grafana/otel-lgtm:0.29.2
    ports:
      - "3001:3000"
      - "4317:4317"
      - "4318:4318"
    volumes:
      - lgtm-data:/data

volumes:
  lgtm-data:
