/** biome-ignore-all lint/style/useNamingConvention: safe */

/** biome-ignore-all lint/suspicious/noExplicitAny: safe  */

// @ts-nocheck

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./app/__root";
import { Route as TermsRouteImport } from "./app/terms";
import { Route as SitemapDotxmlRouteImport } from "./app/sitemap[.]xml";
import { Route as PrivacyPolicyRouteImport } from "./app/privacy-policy";
import { Route as LlmsDottxtRouteImport } from "./app/llms[.]txt";
import { Route as LlmsFullDottxtRouteImport } from "./app/llms-full[.]txt";
import { Route as BlogRouteRouteImport } from "./app/blog/route";
import { Route as IndexRouteImport } from "./app/index";
import { Route as ChangelogIndexRouteImport } from "./app/changelog/index";
import { Route as BlogIndexRouteImport } from "./app/blog/index";
import { Route as DocsSplatRouteImport } from "./app/docs/$";
import { Route as BlogSlugRouteImport } from "./app/blog/$slug";
import { Route as ApiSearchRouteImport } from "./app/api/search";
import { Route as ApiOgRouteImport } from "./app/api/og";
import { Route as ApiChatRouteImport } from "./app/api/chat";
import { Route as LlmsDotmdxDocsSplatRouteImport } from "./app/llms[.]mdx.docs.$";
import { Route as ApiPhSplatRouteImport } from "./app/api/ph/$";

const TermsRoute = TermsRouteImport.update({
  id: "/terms",
  path: "/terms",
  getParentRoute: () => rootRouteImport,
} as any);
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: "/sitemap.xml",
  path: "/sitemap.xml",
  getParentRoute: () => rootRouteImport,
} as any);
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: "/privacy-policy",
  path: "/privacy-policy",
  getParentRoute: () => rootRouteImport,
} as any);
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: "/llms.txt",
  path: "/llms.txt",
  getParentRoute: () => rootRouteImport,
} as any);
const LlmsFullDottxtRoute = LlmsFullDottxtRouteImport.update({
  id: "/llms-full.txt",
  path: "/llms-full.txt",
  getParentRoute: () => rootRouteImport,
} as any);
const BlogRouteRoute = BlogRouteRouteImport.update({
  id: "/blog",
  path: "/blog",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const ChangelogIndexRoute = ChangelogIndexRouteImport.update({
  id: "/changelog/",
  path: "/changelog/",
  getParentRoute: () => rootRouteImport,
} as any);
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => BlogRouteRoute,
} as any);
const DocsSplatRoute = DocsSplatRouteImport.update({
  id: "/docs/$",
  path: "/docs/$",
  getParentRoute: () => rootRouteImport,
} as any);
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: "/$slug",
  path: "/$slug",
  getParentRoute: () => BlogRouteRoute,
} as any);
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: "/api/search",
  path: "/api/search",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiOgRoute = ApiOgRouteImport.update({
  id: "/api/og",
  path: "/api/og",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiChatRoute = ApiChatRouteImport.update({
  id: "/api/chat",
  path: "/api/chat",
  getParentRoute: () => rootRouteImport,
} as any);
const LlmsDotmdxDocsSplatRoute = LlmsDotmdxDocsSplatRouteImport.update({
  id: "/llms.mdx/docs/$",
  path: "/llms.mdx/docs/$",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiPhSplatRoute = ApiPhSplatRouteImport.update({
  id: "/api/ph/$",
  path: "/api/ph/$",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/blog": typeof BlogRouteRouteWithChildren;
  "/llms-full.txt": typeof LlmsFullDottxtRoute;
  "/llms.txt": typeof LlmsDottxtRoute;
  "/privacy-policy": typeof PrivacyPolicyRoute;
  "/sitemap.xml": typeof SitemapDotxmlRoute;
  "/terms": typeof TermsRoute;
  "/api/chat": typeof ApiChatRoute;
  "/api/og": typeof ApiOgRoute;
  "/api/search": typeof ApiSearchRoute;
  "/blog/$slug": typeof BlogSlugRoute;
  "/docs/$": typeof DocsSplatRoute;
  "/blog/": typeof BlogIndexRoute;
  "/changelog/": typeof ChangelogIndexRoute;
  "/api/ph/$": typeof ApiPhSplatRoute;
  "/llms.mdx/docs/$": typeof LlmsDotmdxDocsSplatRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/llms-full.txt": typeof LlmsFullDottxtRoute;
  "/llms.txt": typeof LlmsDottxtRoute;
  "/privacy-policy": typeof PrivacyPolicyRoute;
  "/sitemap.xml": typeof SitemapDotxmlRoute;
  "/terms": typeof TermsRoute;
  "/api/chat": typeof ApiChatRoute;
  "/api/og": typeof ApiOgRoute;
  "/api/search": typeof ApiSearchRoute;
  "/blog/$slug": typeof BlogSlugRoute;
  "/docs/$": typeof DocsSplatRoute;
  "/blog": typeof BlogIndexRoute;
  "/changelog": typeof ChangelogIndexRoute;
  "/api/ph/$": typeof ApiPhSplatRoute;
  "/llms.mdx/docs/$": typeof LlmsDotmdxDocsSplatRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/blog": typeof BlogRouteRouteWithChildren;
  "/llms-full.txt": typeof LlmsFullDottxtRoute;
  "/llms.txt": typeof LlmsDottxtRoute;
  "/privacy-policy": typeof PrivacyPolicyRoute;
  "/sitemap.xml": typeof SitemapDotxmlRoute;
  "/terms": typeof TermsRoute;
  "/api/chat": typeof ApiChatRoute;
  "/api/og": typeof ApiOgRoute;
  "/api/search": typeof ApiSearchRoute;
  "/blog/$slug": typeof BlogSlugRoute;
  "/docs/$": typeof DocsSplatRoute;
  "/blog/": typeof BlogIndexRoute;
  "/changelog/": typeof ChangelogIndexRoute;
  "/api/ph/$": typeof ApiPhSplatRoute;
  "/llms.mdx/docs/$": typeof LlmsDotmdxDocsSplatRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/blog"
    | "/llms-full.txt"
    | "/llms.txt"
    | "/privacy-policy"
    | "/sitemap.xml"
    | "/terms"
    | "/api/chat"
    | "/api/og"
    | "/api/search"
    | "/blog/$slug"
    | "/docs/$"
    | "/blog/"
    | "/changelog/"
    | "/api/ph/$"
    | "/llms.mdx/docs/$";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/llms-full.txt"
    | "/llms.txt"
    | "/privacy-policy"
    | "/sitemap.xml"
    | "/terms"
    | "/api/chat"
    | "/api/og"
    | "/api/search"
    | "/blog/$slug"
    | "/docs/$"
    | "/blog"
    | "/changelog"
    | "/api/ph/$"
    | "/llms.mdx/docs/$";
  id:
    | "__root__"
    | "/"
    | "/blog"
    | "/llms-full.txt"
    | "/llms.txt"
    | "/privacy-policy"
    | "/sitemap.xml"
    | "/terms"
    | "/api/chat"
    | "/api/og"
    | "/api/search"
    | "/blog/$slug"
    | "/docs/$"
    | "/blog/"
    | "/changelog/"
    | "/api/ph/$"
    | "/llms.mdx/docs/$";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  BlogRouteRoute: typeof BlogRouteRouteWithChildren;
  LlmsFullDottxtRoute: typeof LlmsFullDottxtRoute;
  LlmsDottxtRoute: typeof LlmsDottxtRoute;
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute;
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute;
  TermsRoute: typeof TermsRoute;
  ApiChatRoute: typeof ApiChatRoute;
  ApiOgRoute: typeof ApiOgRoute;
  ApiSearchRoute: typeof ApiSearchRoute;
  DocsSplatRoute: typeof DocsSplatRoute;
  ChangelogIndexRoute: typeof ChangelogIndexRoute;
  ApiPhSplatRoute: typeof ApiPhSplatRoute;
  LlmsDotmdxDocsSplatRoute: typeof LlmsDotmdxDocsSplatRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/terms": {
      id: "/terms";
      path: "/terms";
      fullPath: "/terms";
      preLoaderRoute: typeof TermsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/sitemap.xml": {
      id: "/sitemap.xml";
      path: "/sitemap.xml";
      fullPath: "/sitemap.xml";
      preLoaderRoute: typeof SitemapDotxmlRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/privacy-policy": {
      id: "/privacy-policy";
      path: "/privacy-policy";
      fullPath: "/privacy-policy";
      preLoaderRoute: typeof PrivacyPolicyRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/llms.txt": {
      id: "/llms.txt";
      path: "/llms.txt";
      fullPath: "/llms.txt";
      preLoaderRoute: typeof LlmsDottxtRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/llms-full.txt": {
      id: "/llms-full.txt";
      path: "/llms-full.txt";
      fullPath: "/llms-full.txt";
      preLoaderRoute: typeof LlmsFullDottxtRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/blog": {
      id: "/blog";
      path: "/blog";
      fullPath: "/blog";
      preLoaderRoute: typeof BlogRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/changelog/": {
      id: "/changelog/";
      path: "/changelog";
      fullPath: "/changelog/";
      preLoaderRoute: typeof ChangelogIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/blog/": {
      id: "/blog/";
      path: "/";
      fullPath: "/blog/";
      preLoaderRoute: typeof BlogIndexRouteImport;
      parentRoute: typeof BlogRouteRoute;
    };
    "/docs/$": {
      id: "/docs/$";
      path: "/docs/$";
      fullPath: "/docs/$";
      preLoaderRoute: typeof DocsSplatRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/blog/$slug": {
      id: "/blog/$slug";
      path: "/$slug";
      fullPath: "/blog/$slug";
      preLoaderRoute: typeof BlogSlugRouteImport;
      parentRoute: typeof BlogRouteRoute;
    };
    "/api/search": {
      id: "/api/search";
      path: "/api/search";
      fullPath: "/api/search";
      preLoaderRoute: typeof ApiSearchRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/og": {
      id: "/api/og";
      path: "/api/og";
      fullPath: "/api/og";
      preLoaderRoute: typeof ApiOgRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/chat": {
      id: "/api/chat";
      path: "/api/chat";
      fullPath: "/api/chat";
      preLoaderRoute: typeof ApiChatRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/llms.mdx/docs/$": {
      id: "/llms.mdx/docs/$";
      path: "/llms.mdx/docs/$";
      fullPath: "/llms.mdx/docs/$";
      preLoaderRoute: typeof LlmsDotmdxDocsSplatRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/ph/$": {
      id: "/api/ph/$";
      path: "/api/ph/$";
      fullPath: "/api/ph/$";
      preLoaderRoute: typeof ApiPhSplatRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

interface BlogRouteRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute;
  BlogIndexRoute: typeof BlogIndexRoute;
}

const BlogRouteRouteChildren: BlogRouteRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
};

const BlogRouteRouteWithChildren = BlogRouteRoute._addFileChildren(
  BlogRouteRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogRouteRoute: BlogRouteRouteWithChildren,
  LlmsFullDottxtRoute: LlmsFullDottxtRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  ApiChatRoute: ApiChatRoute,
  ApiOgRoute: ApiOgRoute,
  ApiSearchRoute: ApiSearchRoute,
  DocsSplatRoute: DocsSplatRoute,
  ChangelogIndexRoute: ChangelogIndexRoute,
  ApiPhSplatRoute: ApiPhSplatRoute,
  LlmsDotmdxDocsSplatRoute: LlmsDotmdxDocsSplatRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from "./router.tsx";
import type { startInstance } from "./start.ts";
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
    config: Awaited<ReturnType<typeof startInstance.getOptions>>;
  }
}
