export const cryptoPurpose = {
  platformInvitation: "auth.platform-invitation.token",
  googleState: "auth.google.state",
  googleNonce: "auth.google.nonce",
  googleBrowser: "auth.google.browser",
  googleVerifier: "auth.google.pkce",
  betaInvite: "auth.beta-invite.code",
  betaAdmissionToken: "auth.beta-admission.token",
  magicLinkToken: "auth.magic-link.token",
  magicLinkCode: "auth.magic-link.code",
  sessionToken: "auth.session.token",
  apiKey: "auth.api-key",
  emailOutbox: "email.outbox.payload",
  providerCredential: "core.credentials.payload",
  sessionKeyPolicies: "session-key.policies",
  executionRequest: "execution.request",
  signatureRequest: "signature.request",
  oauthAuthorizationCode: "auth.oauth.authorization-code",
  oauthAccessToken: "auth.oauth.access-token",
  oauthRefreshToken: "auth.oauth.refresh-token",
  oauthDeviceCode: "auth.oauth.device-code",
  oauthUserCode: "auth.oauth.user-code",
} as const;
