/** biome-ignore-all lint/style/useNamingConvention: safe */

/** biome-ignore-all lint/suspicious/noExplicitAny: safe  */

// @ts-nocheck

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./app/__root";
import { Route as LlmsDottxtRouteImport } from "./app/llms[.]txt";
import { Route as LlmsFullDottxtRouteImport } from "./app/llms-full[.]txt";
import { Route as DashboardRouteRouteImport } from "./app/dashboard/route";
import { Route as IndexRouteImport } from "./app/index";
import { Route as DashboardIndexRouteImport } from "./app/dashboard/index";
import { Route as DocsSplatRouteImport } from "./app/docs/$";
import { Route as ApiSearchRouteImport } from "./app/api/search";
import { Route as DashboardSettingsIndexRouteImport } from "./app/dashboard/settings/index";
import { Route as DashboardSessionKeysIndexRouteImport } from "./app/dashboard/session-keys/index";
import { Route as DashboardSecurityIndexRouteImport } from "./app/dashboard/security/index";
import { Route as DashboardPermissionsIndexRouteImport } from "./app/dashboard/permissions/index";
import { Route as DashboardAssetsIndexRouteImport } from "./app/dashboard/assets/index";
import { Route as DashboardActivityIndexRouteImport } from "./app/dashboard/activity/index";
import { Route as LlmsDotmdxDocsSplatRouteImport } from "./app/llms[.]mdx.docs.$";

const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: "/llms.txt",
  path: "/llms.txt",
  getParentRoute: () => rootRouteImport,
} as any);
const LlmsFullDottxtRoute = LlmsFullDottxtRouteImport.update({
  id: "/llms-full.txt",
  path: "/llms-full.txt",
  getParentRoute: () => rootRouteImport,
} as any);
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: "/dashboard",
  path: "/dashboard",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => DashboardRouteRoute,
} as any);
const DocsSplatRoute = DocsSplatRouteImport.update({
  id: "/docs/$",
  path: "/docs/$",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: "/api/search",
  path: "/api/search",
  getParentRoute: () => rootRouteImport,
} as any);
const DashboardSettingsIndexRoute = DashboardSettingsIndexRouteImport.update({
  id: "/settings/",
  path: "/settings/",
  getParentRoute: () => DashboardRouteRoute,
} as any);
const DashboardSessionKeysIndexRoute =
  DashboardSessionKeysIndexRouteImport.update({
    id: "/session-keys/",
    path: "/session-keys/",
    getParentRoute: () => DashboardRouteRoute,
  } as any);
const DashboardSecurityIndexRoute = DashboardSecurityIndexRouteImport.update({
  id: "/security/",
  path: "/security/",
  getParentRoute: () => DashboardRouteRoute,
} as any);
const DashboardPermissionsIndexRoute =
  DashboardPermissionsIndexRouteImport.update({
    id: "/permissions/",
    path: "/permissions/",
    getParentRoute: () => DashboardRouteRoute,
  } as any);
const DashboardAssetsIndexRoute = DashboardAssetsIndexRouteImport.update({
  id: "/assets/",
  path: "/assets/",
  getParentRoute: () => DashboardRouteRoute,
} as any);
const DashboardActivityIndexRoute = DashboardActivityIndexRouteImport.update({
  id: "/activity/",
  path: "/activity/",
  getParentRoute: () => DashboardRouteRoute,
} as any);
const LlmsDotmdxDocsSplatRoute = LlmsDotmdxDocsSplatRouteImport.update({
  id: "/llms.mdx/docs/$",
  path: "/llms.mdx/docs/$",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/dashboard": typeof DashboardRouteRouteWithChildren;
  "/llms-full.txt": typeof LlmsFullDottxtRoute;
  "/llms.txt": typeof LlmsDottxtRoute;
  "/api/search": typeof ApiSearchRoute;
  "/docs/$": typeof DocsSplatRoute;
  "/dashboard/": typeof DashboardIndexRoute;
  "/llms.mdx/docs/$": typeof LlmsDotmdxDocsSplatRoute;
  "/dashboard/activity/": typeof DashboardActivityIndexRoute;
  "/dashboard/assets/": typeof DashboardAssetsIndexRoute;
  "/dashboard/permissions/": typeof DashboardPermissionsIndexRoute;
  "/dashboard/security/": typeof DashboardSecurityIndexRoute;
  "/dashboard/session-keys/": typeof DashboardSessionKeysIndexRoute;
  "/dashboard/settings/": typeof DashboardSettingsIndexRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/llms-full.txt": typeof LlmsFullDottxtRoute;
  "/llms.txt": typeof LlmsDottxtRoute;
  "/api/search": typeof ApiSearchRoute;
  "/docs/$": typeof DocsSplatRoute;
  "/dashboard": typeof DashboardIndexRoute;
  "/llms.mdx/docs/$": typeof LlmsDotmdxDocsSplatRoute;
  "/dashboard/activity": typeof DashboardActivityIndexRoute;
  "/dashboard/assets": typeof DashboardAssetsIndexRoute;
  "/dashboard/permissions": typeof DashboardPermissionsIndexRoute;
  "/dashboard/security": typeof DashboardSecurityIndexRoute;
  "/dashboard/session-keys": typeof DashboardSessionKeysIndexRoute;
  "/dashboard/settings": typeof DashboardSettingsIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/dashboard": typeof DashboardRouteRouteWithChildren;
  "/llms-full.txt": typeof LlmsFullDottxtRoute;
  "/llms.txt": typeof LlmsDottxtRoute;
  "/api/search": typeof ApiSearchRoute;
  "/docs/$": typeof DocsSplatRoute;
  "/dashboard/": typeof DashboardIndexRoute;
  "/llms.mdx/docs/$": typeof LlmsDotmdxDocsSplatRoute;
  "/dashboard/activity/": typeof DashboardActivityIndexRoute;
  "/dashboard/assets/": typeof DashboardAssetsIndexRoute;
  "/dashboard/permissions/": typeof DashboardPermissionsIndexRoute;
  "/dashboard/security/": typeof DashboardSecurityIndexRoute;
  "/dashboard/session-keys/": typeof DashboardSessionKeysIndexRoute;
  "/dashboard/settings/": typeof DashboardSettingsIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/dashboard"
    | "/llms-full.txt"
    | "/llms.txt"
    | "/api/search"
    | "/docs/$"
    | "/dashboard/"
    | "/llms.mdx/docs/$"
    | "/dashboard/activity/"
    | "/dashboard/assets/"
    | "/dashboard/permissions/"
    | "/dashboard/security/"
    | "/dashboard/session-keys/"
    | "/dashboard/settings/";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/llms-full.txt"
    | "/llms.txt"
    | "/api/search"
    | "/docs/$"
    | "/dashboard"
    | "/llms.mdx/docs/$"
    | "/dashboard/activity"
    | "/dashboard/assets"
    | "/dashboard/permissions"
    | "/dashboard/security"
    | "/dashboard/session-keys"
    | "/dashboard/settings";
  id:
    | "__root__"
    | "/"
    | "/dashboard"
    | "/llms-full.txt"
    | "/llms.txt"
    | "/api/search"
    | "/docs/$"
    | "/dashboard/"
    | "/llms.mdx/docs/$"
    | "/dashboard/activity/"
    | "/dashboard/assets/"
    | "/dashboard/permissions/"
    | "/dashboard/security/"
    | "/dashboard/session-keys/"
    | "/dashboard/settings/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren;
  LlmsFullDottxtRoute: typeof LlmsFullDottxtRoute;
  LlmsDottxtRoute: typeof LlmsDottxtRoute;
  ApiSearchRoute: typeof ApiSearchRoute;
  DocsSplatRoute: typeof DocsSplatRoute;
  LlmsDotmdxDocsSplatRoute: typeof LlmsDotmdxDocsSplatRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/llms.txt": {
      id: "/llms.txt";
      path: "/llms.txt";
      fullPath: "/llms.txt";
      preLoaderRoute: typeof LlmsDottxtRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/llms-full.txt": {
      id: "/llms-full.txt";
      path: "/llms-full.txt";
      fullPath: "/llms-full.txt";
      preLoaderRoute: typeof LlmsFullDottxtRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/dashboard": {
      id: "/dashboard";
      path: "/dashboard";
      fullPath: "/dashboard";
      preLoaderRoute: typeof DashboardRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/dashboard/": {
      id: "/dashboard/";
      path: "/";
      fullPath: "/dashboard/";
      preLoaderRoute: typeof DashboardIndexRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    "/docs/$": {
      id: "/docs/$";
      path: "/docs/$";
      fullPath: "/docs/$";
      preLoaderRoute: typeof DocsSplatRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/search": {
      id: "/api/search";
      path: "/api/search";
      fullPath: "/api/search";
      preLoaderRoute: typeof ApiSearchRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/dashboard/settings/": {
      id: "/dashboard/settings/";
      path: "/settings";
      fullPath: "/dashboard/settings/";
      preLoaderRoute: typeof DashboardSettingsIndexRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    "/dashboard/session-keys/": {
      id: "/dashboard/session-keys/";
      path: "/session-keys";
      fullPath: "/dashboard/session-keys/";
      preLoaderRoute: typeof DashboardSessionKeysIndexRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    "/dashboard/security/": {
      id: "/dashboard/security/";
      path: "/security";
      fullPath: "/dashboard/security/";
      preLoaderRoute: typeof DashboardSecurityIndexRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    "/dashboard/permissions/": {
      id: "/dashboard/permissions/";
      path: "/permissions";
      fullPath: "/dashboard/permissions/";
      preLoaderRoute: typeof DashboardPermissionsIndexRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    "/dashboard/assets/": {
      id: "/dashboard/assets/";
      path: "/assets";
      fullPath: "/dashboard/assets/";
      preLoaderRoute: typeof DashboardAssetsIndexRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    "/dashboard/activity/": {
      id: "/dashboard/activity/";
      path: "/activity";
      fullPath: "/dashboard/activity/";
      preLoaderRoute: typeof DashboardActivityIndexRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    "/llms.mdx/docs/$": {
      id: "/llms.mdx/docs/$";
      path: "/llms.mdx/docs/$";
      fullPath: "/llms.mdx/docs/$";
      preLoaderRoute: typeof LlmsDotmdxDocsSplatRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

interface DashboardRouteRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute;
  DashboardActivityIndexRoute: typeof DashboardActivityIndexRoute;
  DashboardAssetsIndexRoute: typeof DashboardAssetsIndexRoute;
  DashboardPermissionsIndexRoute: typeof DashboardPermissionsIndexRoute;
  DashboardSecurityIndexRoute: typeof DashboardSecurityIndexRoute;
  DashboardSessionKeysIndexRoute: typeof DashboardSessionKeysIndexRoute;
  DashboardSettingsIndexRoute: typeof DashboardSettingsIndexRoute;
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardActivityIndexRoute: DashboardActivityIndexRoute,
  DashboardAssetsIndexRoute: DashboardAssetsIndexRoute,
  DashboardPermissionsIndexRoute: DashboardPermissionsIndexRoute,
  DashboardSecurityIndexRoute: DashboardSecurityIndexRoute,
  DashboardSessionKeysIndexRoute: DashboardSessionKeysIndexRoute,
  DashboardSettingsIndexRoute: DashboardSettingsIndexRoute,
};

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  LlmsFullDottxtRoute: LlmsFullDottxtRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  ApiSearchRoute: ApiSearchRoute,
  DocsSplatRoute: DocsSplatRoute,
  LlmsDotmdxDocsSplatRoute: LlmsDotmdxDocsSplatRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from "./router.tsx";
import type { startInstance } from "./start.ts";
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
    config: Awaited<ReturnType<typeof startInstance.getOptions>>;
  }
}
