export type IconCategory =
  | "general"
  | "user"
  | "communication"
  | "files"
  | "time"
  | "finance"
  | "media"
  | "devices"
  | "actions"
  | "alerts"
  | "nature"
  | "commerce";

export type IconData = {
  icon: Icon;
  name: string;
  component: string;
  category: IconCategory;
  tags: string[];
};

import {
  HouseIcon,
  GridFourIcon,
  ListIcon,
  KanbanIcon,
  CompassIcon,
  MapTrifoldIcon,
  GlobeIcon,
  FlagIcon,
  BookmarkIcon,
  TagIcon,
  PushPinIcon,
  LayoutIcon,
  ColumnsIcon,
  RowsIcon,
  StackIcon,
  CubeIcon,
  PuzzlePieceIcon,
  TargetIcon,
  RocketIcon,
  LightbulbIcon,
  BrainIcon,
  MagicWandIcon,
  SparkleIcon,
  InfinityIcon,
  ShapesIcon,
  PaletteIcon,
  PenIcon,
  PencilIcon,
  HighlighterIcon,
  EraserIcon,
  UserIcon,
  UsersIcon,
  UserPlusIcon,
  UserMinusIcon,
  UserGearIcon,
  UserCircleIcon,
  UserListIcon,
  UserCheckIcon,
  UserSwitchIcon,
  PersonIcon,
  PersonSimpleRunIcon,
  PersonSimpleWalkIcon,
  PersonSimpleHikeIcon,
  PlusIcon,
  MinusIcon,
  CheckIcon,
  XIcon,
  CheckCircleIcon,
  XCircleIcon,
  CopyIcon,
  DownloadIcon,
  UploadIcon,
  ShareIcon,
  ShareNetworkIcon,
  LinkIcon,
  LinkBreakIcon,
  MagnifyingGlassIcon,
  FunnelIcon,
  SortAscendingIcon,
  SortDescendingIcon,
  ArrowsClockwiseIcon,
  ArrowsCounterClockwiseIcon,
  RepeatIcon,
  RepeatOnceIcon,
  ShuffleIcon,
  ArrowUpIcon,
  ArrowDownIcon,
  ArrowLeftIcon,
  ArrowRightIcon,
  ArrowUpRightIcon,
  ArrowDownLeftIcon,
  ArrowBendRightUpIcon,
  CaretUpIcon,
  CaretDownIcon,
  CaretLeftIcon,
  CaretRightIcon,
  DotsThreeIcon,
  DotsNineIcon,
  SelectionIcon,
  CropIcon,
  FlipHorizontalIcon,
  FlipVerticalIcon,
  ResizeIcon,
  FileIcon,
  FileTextIcon,
  FileCodeIcon,
  FileImageIcon,
  FileAudioIcon,
  FileVideoIcon,
  FileZipIcon,
  FilePdfIcon,
  FileDocIcon,
  FileJsIcon,
  FileTsIcon,
  FolderIcon,
  FolderOpenIcon,
  FolderPlusIcon,
  FolderMinusIcon,
  FolderLockIcon,
  ClipboardIcon,
  ClipboardTextIcon,
  NoteIcon,
  NotebookIcon,
  NotepadIcon,
  ArticleIcon,
  NewspaperIcon,
  PrinterIcon,
  ScanIcon,
  PresentationIcon,
  PresentationChartIcon,
  TerminalIcon,
  TerminalWindowIcon,
  CodeIcon,
  PlayIcon,
  PauseIcon,
  StopIcon,
  CameraIcon,
  VideoIcon,
  MicrophoneIcon,
  SpeakerHighIcon,
  MusicNoteIcon,
  LaptopIcon,
  MonitorIcon,
  DeviceMobileIcon,
  CpuIcon,
  DatabaseIcon,
  WifiHighIcon,
  BluetoothIcon,
  WarningIcon,
  InfoIcon,
  QuestionIcon,
  ShieldIcon,
  LockIcon,
  StarIcon,
  HeartIcon,
  FireIcon,
  LeafIcon,
  SunIcon,
  MoonIcon,
  CloudIcon,
  SnowflakeIcon,
  ShoppingCartIcon,
  ShoppingBagIcon,
  StorefrontIcon,
  PackageIcon,
  TruckIcon,
  GiftIcon,
  ReceiptIcon,
  WalletIcon,
  type Icon,
  HandshakeIcon,
  HandHeartIcon,
  HandsClappingIcon,
  HandsPrayingIcon,
  UserFocusIcon,
  UserSoundIcon,
  UserRectangleIcon,
  UserSquareIcon,
  UsersThreeIcon,
  UsersFourIcon,
  IdentificationCardIcon,
  IdentificationBadgeIcon,
} from "@phosphor-icons/react";

// oxfmt-ignore
export const ICON_DATA: IconData[] = [
    // GENERAL (30)
  { name: "house", component: "House", category: "general", tags: ["home", "dashboard"], icon: HouseIcon },
  { name: "grid", component: "GridFour", category: "general", tags: ["apps", "menu"], icon: GridFourIcon },
  { name: "list", component: "List", category: "general", tags: ["items", "menu"] , icon: ListIcon },
  { name: "kanban", component: "Kanban", category: "general", tags: ["board", "tasks"], icon: KanbanIcon },
  { name: "compass", component: "Compass", category: "general", tags: ["explore", "navigation"], icon: CompassIcon },
  { name: "map", component: "MapTrifold", category: "general", tags: ["location", "map"], icon: MapTrifoldIcon },
  { name: "globe", component: "Globe", category: "general", tags: ["internet", "world"], icon: GlobeIcon },
  { name: "flag", component: "Flag", category: "general", tags: ["mark", "important"], icon: FlagIcon },
  { name: "bookmark", component: "Bookmark", category: "general", tags: ["save", "favorite"], icon: BookmarkIcon },
  { name: "tag", component: "Tag", category: "general", tags: ["label", "category"], icon: TagIcon },
  { name: "pin", component: "PushPin", category: "general", tags: ["pin"], icon: PushPinIcon },
  { name: "layout", component: "Layout", category: "general", tags: ["ui"], icon: LayoutIcon },
  { name: "columns", component: "Columns", category: "general", tags: ["grid"] , icon: ColumnsIcon },
  { name: "rows", component: "Rows", category: "general", tags: ["list"] , icon: RowsIcon },
  { name: "stack", component: "Stack", category: "general", tags: ["layers"] , icon: StackIcon },
  { name: "cube", component: "Cube", category: "general", tags: ["block"] , icon: CubeIcon },
  { name: "puzzle", component: "PuzzlePiece", category: "general", tags: ["logic"] , icon: PuzzlePieceIcon },
  { name: "target", component: "Target", category: "general", tags: ["goal"] , icon: TargetIcon },
  { name: "rocket", component: "Rocket", category: "general", tags: ["launch"] , icon: RocketIcon },
  { name: "lightbulb", component: "Lightbulb", category: "general", tags: ["idea"] , icon: LightbulbIcon },
  { name: "brain", component: "Brain", category: "general", tags: ["thinking"] , icon: BrainIcon },
  { name: "magic", component: "MagicWand", category: "general", tags: ["ai"] , icon: MagicWandIcon },
  { name: "sparkle", component: "Sparkle", category: "general", tags: ["magic"] , icon: SparkleIcon },
  { name: "infinity", component: "Infinity", category: "general", tags: ["loop"] , icon: InfinityIcon },
  { name: "shapes", component: "Shapes", category: "general", tags: ["design"] , icon: ShapesIcon },
  { name: "palette", component: "Palette", category: "general", tags: ["color"] , icon: PaletteIcon },
  { name: "pen", component: "Pen", category: "general", tags: ["draw"] , icon: PenIcon },
  { name: "pencil", component: "Pencil", category: "general", tags: ["edit"] , icon: PencilIcon },
  { name: "highlighter", component: "Highlighter", category: "general", tags: ["highlight"] , icon: HighlighterIcon },
  { name: "eraser", component: "Eraser", category: "general", tags: ["erase"] , icon: EraserIcon },

  // USER (25)
  { name: "user", component: "User", category: "user", tags: ["profile"] , icon: UserIcon },
  { name: "users", component: "Users", category: "user", tags: ["team"] , icon: UsersIcon },
  { name: "user-plus", component: "UserPlus", category: "user", tags: ["invite"] , icon: UserPlusIcon },
  { name: "user-minus", component: "UserMinus", category: "user", tags: ["remove"] , icon: UserMinusIcon },
  { name: "user-gear", component: "UserGear", category: "user", tags: ["settings"] , icon: UserGearIcon },
  { name: "user-circle", component: "UserCircle", category: "user", tags: ["account"] , icon: UserCircleIcon },
  { name: "user-list", component: "UserList", category: "user", tags: ["directory"] , icon: UserListIcon },
  { name: "user-check", component: "UserCheck", category: "user", tags: ["verified"] , icon: UserCheckIcon },
  { name: "user-switch", component: "UserSwitch", category: "user", tags: ["switch"] , icon: UserSwitchIcon },
  { name: "identification", component: "IdentificationCard", category: "user", tags: ["id"] , icon: IdentificationCardIcon },
  { name: "badge", component: "IdentificationBadge", category: "user", tags: ["badge"] , icon: IdentificationBadgeIcon },
  { name: "person", component: "Person", category: "user", tags: ["human"] , icon: PersonIcon },
  { name: "handshake", component: "Handshake", category: "user", tags: ["deal"] , icon: HandshakeIcon },
  { name: "hand-heart", component: "HandHeart", category: "user", tags: ["care"] , icon: HandHeartIcon },
  { name: "hands-clapping", component: "HandsClapping", category: "user", tags: ["clap"] , icon: HandsClappingIcon },
  { name: "hands-praying", component: "HandsPraying", category: "user", tags: ["pray"] , icon: HandsPrayingIcon },
  { name: "user-focus", component: "UserFocus", category: "user", tags: ["focus"] , icon: UserFocusIcon },
  { name: "user-sound", component: "UserSound", category: "user", tags: ["audio"] , icon: UserSoundIcon },
  { name: "user-rectangle", component: "UserRectangle", category: "user", tags: ["profile"] , icon: UserRectangleIcon },
  { name: "user-square", component: "UserSquare", category: "user", tags: ["profile"] , icon: UserSquareIcon },
  { name: "users-three", component: "UsersThree", category: "user", tags: ["group"] , icon: UsersThreeIcon },
  { name: "users-four", component: "UsersFour", category: "user", tags: ["team"] , icon: UsersFourIcon },
  { name: "person-run", component: "PersonSimpleRun", category: "user", tags: ["run"] , icon: PersonSimpleRunIcon },
  { name: "person-walk", component: "PersonSimpleWalk", category: "user", tags: ["walk"] , icon: PersonSimpleWalkIcon },
  { name: "person-hike", component: "PersonSimpleHike", category: "user", tags: ["hike"] , icon: PersonSimpleHikeIcon },

  // ACTIONS (40)
  { name: "plus", component: "Plus", category: "actions", tags: ["add"] , icon: PlusIcon },
  { name: "minus", component: "Minus", category: "actions", tags: ["remove"] , icon: MinusIcon },
  { name: "check", component: "Check", category: "actions", tags: ["done"] , icon: CheckIcon },
  { name: "x", component: "X", category: "actions", tags: ["close"] , icon: XIcon },
  { name: "check-circle", component: "CheckCircle", category: "actions", tags: ["success"] , icon: CheckCircleIcon },
  { name: "x-circle", component: "XCircle", category: "actions", tags: ["error"] , icon: XCircleIcon },
  { name: "copy", component: "Copy", category: "actions", tags: ["duplicate"] , icon: CopyIcon },
  { name: "download", component: "Download", category: "actions", tags: ["save"] , icon: DownloadIcon },
  { name: "upload", component: "Upload", category: "actions", tags: ["send"] , icon: UploadIcon },
  { name: "share", component: "Share", category: "actions", tags: ["export"] , icon: ShareIcon },
  { name: "share-network", component: "ShareNetwork", category: "actions", tags: ["social"] , icon: ShareNetworkIcon },
  { name: "link", component: "Link", category: "actions", tags: ["url"] , icon: LinkIcon },
  { name: "link-break", component: "LinkBreak", category: "actions", tags: ["unlink"] , icon: LinkBreakIcon },
  { name: "search", component: "MagnifyingGlass", category: "actions", tags: ["find"] , icon: MagnifyingGlassIcon },
  { name: "filter", component: "Funnel", category: "actions", tags: ["sort"] , icon: FunnelIcon },
  { name: "sort-asc", component: "SortAscending", category: "actions", tags: ["ascending"] , icon: SortAscendingIcon },
  { name: "sort-desc", component: "SortDescending", category: "actions", tags: ["descending"] , icon: SortDescendingIcon },
  { name: "arrows-clockwise", component: "ArrowsClockwise", category: "actions", tags: ["refresh"] , icon: ArrowsClockwiseIcon },
  { name: "arrows-counter", component: "ArrowsCounterClockwise", category: "actions", tags: ["undo"] , icon: ArrowsCounterClockwiseIcon },
  { name: "repeat", component: "Repeat", category: "actions", tags: ["loop"] , icon: RepeatIcon },
  { name: "repeat-once", component: "RepeatOnce", category: "actions", tags: ["once"] , icon: RepeatOnceIcon },
  { name: "shuffle", component: "Shuffle", category: "actions", tags: ["random"] , icon: ShuffleIcon },
  { name: "arrow-up", component: "ArrowUp", category: "actions", tags: ["up"] , icon: ArrowUpIcon },
  { name: "arrow-down", component: "ArrowDown", category: "actions", tags: ["down"] , icon: ArrowDownIcon },
  { name: "arrow-left", component: "ArrowLeft", category: "actions", tags: ["left"] , icon: ArrowLeftIcon },
  { name: "arrow-right", component: "ArrowRight", category: "actions", tags: ["right"] , icon: ArrowRightIcon },
  { name: "arrow-up-right", component: "ArrowUpRight", category: "actions", tags: ["external"] , icon: ArrowUpRightIcon },
  { name: "arrow-down-left", component: "ArrowDownLeft", category: "actions", tags: ["back"] , icon: ArrowDownLeftIcon },
  { name: "arrow-bend", component: "ArrowBendRightUp", category: "actions", tags: ["redirect"] , icon: ArrowBendRightUpIcon },
  { name: "caret-up", component: "CaretUp", category: "actions", tags: ["expand"] , icon: CaretUpIcon },
  { name: "caret-down", component: "CaretDown", category: "actions", tags: ["collapse"] , icon: CaretDownIcon },
  { name: "caret-left", component: "CaretLeft", category: "actions", tags: ["previous"] , icon: CaretLeftIcon },
  { name: "caret-right", component: "CaretRight", category: "actions", tags: ["next"] , icon: CaretRightIcon },
  { name: "dots-three", component: "DotsThree", category: "actions", tags: ["menu"] , icon: DotsThreeIcon },
  { name: "dots-nine", component: "DotsNine", category: "actions", tags: ["grid"] , icon: DotsNineIcon },
  { name: "selection", component: "Selection", category: "actions", tags: ["select"] , icon: SelectionIcon },
  { name: "crop", component: "Crop", category: "actions", tags: ["crop"] , icon: CropIcon },
  { name: "flip-horizontal", component: "FlipHorizontal", category: "actions", tags: ["flip"] , icon: FlipHorizontalIcon },
  { name: "flip-vertical", component: "FlipVertical", category: "actions", tags: ["flip"] , icon: FlipVerticalIcon },
  { name: "resize", component: "Resize", category: "actions", tags: ["resize"] , icon: ResizeIcon },

  // FILES (30)
  { name: "file", component: "File", category: "files", tags: ["doc"] , icon: FileIcon },
  { name: "file-text", component: "FileText", category: "files", tags: ["text"] , icon: FileTextIcon },
  { name: "file-code", component: "FileCode", category: "files", tags: ["code"] , icon: FileCodeIcon },
  { name: "file-image", component: "FileImage", category: "files", tags: ["image"] , icon: FileImageIcon },
  { name: "file-audio", component: "FileAudio", category: "files", tags: ["audio"] , icon: FileAudioIcon },
  { name: "file-video", component: "FileVideo", category: "files", tags: ["video"] , icon: FileVideoIcon },
  { name: "file-zip", component: "FileZip", category: "files", tags: ["archive"] , icon: FileZipIcon },
  { name: "file-pdf", component: "FilePdf", category: "files", tags: ["pdf"] , icon: FilePdfIcon },
  { name: "file-doc", component: "FileDoc", category: "files", tags: ["doc"] , icon: FileDocIcon },
  { name: "file-js", component: "FileJs", category: "files", tags: ["js"] , icon: FileJsIcon },
  { name: "file-ts", component: "FileTs", category: "files", tags: ["ts"] , icon: FileTsIcon },
  { name: "folder", component: "Folder", category: "files", tags: ["directory"] , icon: FolderIcon },
  { name: "folder-open", component: "FolderOpen", category: "files", tags: ["browse"] , icon: FolderOpenIcon },
  { name: "folder-plus", component: "FolderPlus", category: "files", tags: ["add"] , icon: FolderPlusIcon },
  { name: "folder-minus", component: "FolderMinus", category: "files", tags: ["remove"] , icon: FolderMinusIcon },
  { name: "folder-lock", component: "FolderLock", category: "files", tags: ["secure"] , icon: FolderLockIcon },
  { name: "clipboard", component: "Clipboard", category: "files", tags: ["copy"] , icon: ClipboardIcon },
  { name: "clipboard-text", component: "ClipboardText", category: "files", tags: ["text"] , icon: ClipboardTextIcon },
  { name: "note", component: "Note", category: "files", tags: ["note"] , icon: NoteIcon },
  { name: "notebook", component: "Notebook", category: "files", tags: ["notes"] , icon: NotebookIcon },
  { name: "notepad", component: "Notepad", category: "files", tags: ["write"] , icon: NotepadIcon },
  { name: "article", component: "Article", category: "files", tags: ["blog"] , icon: ArticleIcon },
  { name: "newspaper", component: "Newspaper", category: "files", tags: ["news"] , icon: NewspaperIcon },
  { name: "printer", component: "Printer", category: "files", tags: ["print"] , icon: PrinterIcon },
  { name: "scan", component: "Scan", category: "files", tags: ["scan"] , icon: ScanIcon },
  { name: "presentation", component: "Presentation", category: "files", tags: ["slides"] , icon: PresentationIcon },
  { name: "presentation-chart", component: "PresentationChart", category: "files", tags: ["charts"] , icon: PresentationChartIcon },
  { name: "terminal", component: "Terminal", category: "files", tags: ["cli"] , icon: TerminalIcon },
  { name: "terminal-window", component: "TerminalWindow", category: "files", tags: ["cli"] , icon: TerminalWindowIcon },
  { name: "code", component: "Code", category: "files", tags: ["dev"] , icon: CodeIcon },

  // MEDIA + DEVICES + ALERTS + NATURE + COMMERCE (condensed but FULL coverage)
  { name: "play", component: "Play", category: "media", tags: ["start"] , icon: PlayIcon },
  { name: "pause", component: "Pause", category: "media", tags: ["stop"] , icon: PauseIcon },
  { name: "stop", component: "Stop", category: "media", tags: ["end"] , icon: StopIcon },
  { name: "camera", component: "Camera", category: "media", tags: ["photo"] , icon: CameraIcon },
  { name: "video", component: "Video", category: "media", tags: ["media"] , icon: VideoIcon },
  { name: "microphone", component: "Microphone", category: "media", tags: ["record"] , icon: MicrophoneIcon },
  { name: "speaker", component: "SpeakerHigh", category: "media", tags: ["audio"] , icon: SpeakerHighIcon },
  { name: "music", component: "MusicNote", category: "media", tags: ["audio"] , icon: MusicNoteIcon },
  { name: "laptop", component: "Laptop", category: "devices", tags: ["computer"] , icon: LaptopIcon },
  { name: "monitor", component: "Monitor", category: "devices", tags: ["screen"] , icon: MonitorIcon },
  { name: "device-mobile", component: "DeviceMobile", category: "devices", tags: ["phone"] , icon: DeviceMobileIcon },
  { name: "cpu", component: "Cpu", category: "devices", tags: ["processor"] , icon: CpuIcon },
  { name: "database", component: "Database", category: "devices", tags: ["data"] , icon: DatabaseIcon },
  { name: "wifi", component: "WifiHigh", category: "devices", tags: ["internet"] , icon: WifiHighIcon },
  { name: "bluetooth", component: "Bluetooth", category: "devices", tags: ["connect"] , icon: BluetoothIcon },
  { name: "warning", component: "Warning", category: "alerts", tags: ["alert"] , icon: WarningIcon },
  { name: "info", component: "Info", category: "alerts", tags: ["info"] , icon: InfoIcon },
  { name: "question", component: "Question", category: "alerts", tags: ["help"] , icon: QuestionIcon },
  { name: "shield", component: "Shield", category: "alerts", tags: ["security"] , icon: ShieldIcon },
  { name: "lock", component: "Lock", category: "alerts", tags: ["private"] , icon: LockIcon },
  { name: "star", component: "Star", category: "nature", tags: ["favorite"] , icon: StarIcon },
  { name: "heart", component: "Heart", category: "nature", tags: ["like"] , icon: HeartIcon },
  { name: "fire", component: "Fire", category: "nature", tags: ["hot"] , icon: FireIcon },
  { name: "leaf", component: "Leaf", category: "nature", tags: ["eco"] , icon: LeafIcon },
  { name: "sun", component: "Sun", category: "nature", tags: ["day"] , icon: SunIcon },
  { name: "moon", component: "Moon", category: "nature", tags: ["night"] , icon: MoonIcon },
  { name: "cloud", component: "Cloud", category: "nature", tags: ["weather"] , icon: CloudIcon },
  { name: "snow", component: "Snowflake", category: "nature", tags: ["winter"] , icon: SnowflakeIcon },
  { name: "shopping-cart", component: "ShoppingCart", category: "commerce", tags: ["buy"] , icon: ShoppingCartIcon },
  { name: "shopping-bag", component: "ShoppingBag", category: "commerce", tags: ["store"] , icon: ShoppingBagIcon },
  { name: "store", component: "Storefront", category: "commerce", tags: ["shop"] , icon: StorefrontIcon },
  { name: "package", component: "Package", category: "commerce", tags: ["delivery"] , icon: PackageIcon },
  { name: "truck", component: "Truck", category: "commerce", tags: ["shipping"] , icon: TruckIcon },
  { name: "gift", component: "Gift", category: "commerce", tags: ["present"] , icon: GiftIcon },
  { name: "receipt", component: "Receipt", category: "commerce", tags: ["bill"] , icon: ReceiptIcon },
  { name: "wallet", component: "Wallet", category: "commerce", tags: ["pay"] , icon: WalletIcon },
] as const;

export const iconMap: Record<string, IconData> = Object.fromEntries(
  Object.values(ICON_DATA).map((value) => [value.name, value]),
);
