/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedActivityRouteImport } from './routes/_authenticated/activity'
import { Route as AuthenticatedIdentityRouteImport } from './routes/_authenticated/identity'
import { Route as AuthenticatedInboxRouteImport } from './routes/_authenticated/inbox'
import { Route as AuthenticatedMcpRouteImport } from './routes/_authenticated/mcp'
import { Route as AuthenticatedTemplatesRouteImport } from './routes/_authenticated/templates'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as AuthVerifyRouteImport } from './routes/auth/verify'
import { Route as AuthenticatedAccountAccountIdRouteRouteImport } from './routes/_authenticated/account/$accountId/route'
import { Route as AuthenticatedAccountsIndexRouteImport } from './routes/_authenticated/accounts/index'
import { Route as AuthenticatedAccountsNewRouteImport } from './routes/_authenticated/accounts/new'
import { Route as AuthenticatedCliAuthorizeRouteImport } from './routes/_authenticated/cli/authorize'
import { Route as AuthenticatedExecutionExecutionIdRouteImport } from './routes/_authenticated/execution/$executionId'
import { Route as AuthenticatedInvitationsInvitationIdRouteImport } from './routes/_authenticated/invitations/$invitationId'
import { Route as AuthenticatedOauthAuthorizeRouteImport } from './routes/_authenticated/oauth/authorize'
import { Route as AuthenticatedSessionKeySessionKeyIdRouteRouteImport } from './routes/_authenticated/session-key/$sessionKeyId/route'
import { Route as AuthenticatedSessionKeysIndexRouteImport } from './routes/_authenticated/session-keys/index'
import { Route as AuthenticatedSessionKeysNewRouteImport } from './routes/_authenticated/session-keys/new'
import { Route as AuthenticatedSettingsNotificationsRouteImport } from './routes/_authenticated/settings/notifications'
import { Route as AuthenticatedSettingsProfileRouteImport } from './routes/_authenticated/settings/profile'
import { Route as AuthenticatedSettingsSecurityRouteImport } from './routes/_authenticated/settings/security'
import { Route as AuthenticatedWorkspaceNewRouteImport } from './routes/_authenticated/workspace/new'
import { Route as AuthenticatedAccountAccountIdIndexRouteImport } from './routes/_authenticated/account/$accountId/index'
import { Route as AuthenticatedAccountAccountIdAssetsRouteImport } from './routes/_authenticated/account/$accountId/assets'
import { Route as AuthenticatedAccountAccountIdOverviewRouteImport } from './routes/_authenticated/account/$accountId/overview'
import { Route as AuthenticatedAccountAccountIdSessionKeysRouteImport } from './routes/_authenticated/account/$accountId/session-keys'
import { Route as AuthenticatedAccountAccountIdUsageRouteImport } from './routes/_authenticated/account/$accountId/usage'
import { Route as AuthenticatedSessionKeySessionKeyIdIndexRouteImport } from './routes/_authenticated/session-key/$sessionKeyId/index'
import { Route as AuthenticatedSessionKeySessionKeyIdExecutionsRouteImport } from './routes/_authenticated/session-key/$sessionKeyId/executions'
import { Route as AuthenticatedSessionKeySessionKeyIdOverviewRouteImport } from './routes/_authenticated/session-key/$sessionKeyId/overview'
import { Route as AuthenticatedSessionKeySessionKeyIdPoliciesRouteImport } from './routes/_authenticated/session-key/$sessionKeyId/policies'
import { Route as AuthenticatedSettingsWorkspaceIndexRouteImport } from './routes/_authenticated/settings/workspace/index'
import { Route as AuthenticatedSettingsWorkspaceApiKeysRouteImport } from './routes/_authenticated/settings/workspace/api-keys'
import { Route as AuthenticatedSettingsWorkspaceBillingsRouteImport } from './routes/_authenticated/settings/workspace/billings'
import { Route as AuthenticatedSettingsWorkspaceCliAuthorizationsRouteImport } from './routes/_authenticated/settings/workspace/cli-authorizations'
import { Route as AuthenticatedSettingsWorkspaceMcpRouteImport } from './routes/_authenticated/settings/workspace/mcp'
import { Route as AuthenticatedSettingsWorkspaceMembersRouteImport } from './routes/_authenticated/settings/workspace/members'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedActivityRoute = AuthenticatedActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIdentityRoute = AuthenticatedIdentityRouteImport.update({
  id: '/identity',
  path: '/identity',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInboxRoute = AuthenticatedInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMcpRoute = AuthenticatedMcpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTemplatesRoute = AuthenticatedTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthVerifyRoute = AuthVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthenticatedAccountAccountIdRouteRoute =
  AuthenticatedAccountAccountIdRouteRouteImport.update({
    id: '/account/$accountId',
    path: '/account/$accountId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAccountsIndexRoute =
  AuthenticatedAccountsIndexRouteImport.update({
    id: '/accounts/',
    path: '/accounts/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAccountsNewRoute =
  AuthenticatedAccountsNewRouteImport.update({
    id: '/accounts/new',
    path: '/accounts/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCliAuthorizeRoute =
  AuthenticatedCliAuthorizeRouteImport.update({
    id: '/cli/authorize',
    path: '/cli/authorize',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedExecutionExecutionIdRoute =
  AuthenticatedExecutionExecutionIdRouteImport.update({
    id: '/execution/$executionId',
    path: '/execution/$executionId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInvitationsInvitationIdRoute =
  AuthenticatedInvitationsInvitationIdRouteImport.update({
    id: '/invitations/$invitationId',
    path: '/invitations/$invitationId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOauthAuthorizeRoute =
  AuthenticatedOauthAuthorizeRouteImport.update({
    id: '/oauth/authorize',
    path: '/oauth/authorize',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSessionKeySessionKeyIdRouteRoute =
  AuthenticatedSessionKeySessionKeyIdRouteRouteImport.update({
    id: '/session-key/$sessionKeyId',
    path: '/session-key/$sessionKeyId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSessionKeysIndexRoute =
  AuthenticatedSessionKeysIndexRouteImport.update({
    id: '/session-keys/',
    path: '/session-keys/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSessionKeysNewRoute =
  AuthenticatedSessionKeysNewRouteImport.update({
    id: '/session-keys/new',
    path: '/session-keys/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsRouteImport.update({
    id: '/settings/notifications',
    path: '/settings/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsProfileRoute =
  AuthenticatedSettingsProfileRouteImport.update({
    id: '/settings/profile',
    path: '/settings/profile',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsSecurityRoute =
  AuthenticatedSettingsSecurityRouteImport.update({
    id: '/settings/security',
    path: '/settings/security',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWorkspaceNewRoute =
  AuthenticatedWorkspaceNewRouteImport.update({
    id: '/workspace/new',
    path: '/workspace/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAccountAccountIdIndexRoute =
  AuthenticatedAccountAccountIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAccountAccountIdRouteRoute,
  } as any)
const AuthenticatedAccountAccountIdAssetsRoute =
  AuthenticatedAccountAccountIdAssetsRouteImport.update({
    id: '/assets',
    path: '/assets',
    getParentRoute: () => AuthenticatedAccountAccountIdRouteRoute,
  } as any)
const AuthenticatedAccountAccountIdOverviewRoute =
  AuthenticatedAccountAccountIdOverviewRouteImport.update({
    id: '/overview',
    path: '/overview',
    getParentRoute: () => AuthenticatedAccountAccountIdRouteRoute,
  } as any)
const AuthenticatedAccountAccountIdSessionKeysRoute =
  AuthenticatedAccountAccountIdSessionKeysRouteImport.update({
    id: '/session-keys',
    path: '/session-keys',
    getParentRoute: () => AuthenticatedAccountAccountIdRouteRoute,
  } as any)
const AuthenticatedAccountAccountIdUsageRoute =
  AuthenticatedAccountAccountIdUsageRouteImport.update({
    id: '/usage',
    path: '/usage',
    getParentRoute: () => AuthenticatedAccountAccountIdRouteRoute,
  } as any)
const AuthenticatedSessionKeySessionKeyIdIndexRoute =
  AuthenticatedSessionKeySessionKeyIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSessionKeySessionKeyIdRouteRoute,
  } as any)
const AuthenticatedSessionKeySessionKeyIdExecutionsRoute =
  AuthenticatedSessionKeySessionKeyIdExecutionsRouteImport.update({
    id: '/executions',
    path: '/executions',
    getParentRoute: () => AuthenticatedSessionKeySessionKeyIdRouteRoute,
  } as any)
const AuthenticatedSessionKeySessionKeyIdOverviewRoute =
  AuthenticatedSessionKeySessionKeyIdOverviewRouteImport.update({
    id: '/overview',
    path: '/overview',
    getParentRoute: () => AuthenticatedSessionKeySessionKeyIdRouteRoute,
  } as any)
const AuthenticatedSessionKeySessionKeyIdPoliciesRoute =
  AuthenticatedSessionKeySessionKeyIdPoliciesRouteImport.update({
    id: '/policies',
    path: '/policies',
    getParentRoute: () => AuthenticatedSessionKeySessionKeyIdRouteRoute,
  } as any)
const AuthenticatedSettingsWorkspaceIndexRoute =
  AuthenticatedSettingsWorkspaceIndexRouteImport.update({
    id: '/settings/workspace/',
    path: '/settings/workspace/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsWorkspaceApiKeysRoute =
  AuthenticatedSettingsWorkspaceApiKeysRouteImport.update({
    id: '/settings/workspace/api-keys',
    path: '/settings/workspace/api-keys',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsWorkspaceBillingsRoute =
  AuthenticatedSettingsWorkspaceBillingsRouteImport.update({
    id: '/settings/workspace/billings',
    path: '/settings/workspace/billings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsWorkspaceCliAuthorizationsRoute =
  AuthenticatedSettingsWorkspaceCliAuthorizationsRouteImport.update({
    id: '/settings/workspace/cli-authorizations',
    path: '/settings/workspace/cli-authorizations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsWorkspaceMcpRoute =
  AuthenticatedSettingsWorkspaceMcpRouteImport.update({
    id: '/settings/workspace/mcp',
    path: '/settings/workspace/mcp',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsWorkspaceMembersRoute =
  AuthenticatedSettingsWorkspaceMembersRouteImport.update({
    id: '/settings/workspace/members',
    path: '/settings/workspace/members',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/activity': typeof AuthenticatedActivityRoute
  '/identity': typeof AuthenticatedIdentityRoute
  '/inbox': typeof AuthenticatedInboxRoute
  '/mcp': typeof AuthenticatedMcpRoute
  '/templates': typeof AuthenticatedTemplatesRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/auth/': typeof AuthIndexRoute
  '/account/$accountId': typeof AuthenticatedAccountAccountIdRouteRouteWithChildren
  '/session-key/$sessionKeyId': typeof AuthenticatedSessionKeySessionKeyIdRouteRouteWithChildren
  '/accounts/new': typeof AuthenticatedAccountsNewRoute
  '/cli/authorize': typeof AuthenticatedCliAuthorizeRoute
  '/execution/$executionId': typeof AuthenticatedExecutionExecutionIdRoute
  '/invitations/$invitationId': typeof AuthenticatedInvitationsInvitationIdRoute
  '/oauth/authorize': typeof AuthenticatedOauthAuthorizeRoute
  '/session-keys/new': typeof AuthenticatedSessionKeysNewRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/settings/security': typeof AuthenticatedSettingsSecurityRoute
  '/workspace/new': typeof AuthenticatedWorkspaceNewRoute
  '/accounts/': typeof AuthenticatedAccountsIndexRoute
  '/session-keys/': typeof AuthenticatedSessionKeysIndexRoute
  '/account/$accountId/assets': typeof AuthenticatedAccountAccountIdAssetsRoute
  '/account/$accountId/overview': typeof AuthenticatedAccountAccountIdOverviewRoute
  '/account/$accountId/session-keys': typeof AuthenticatedAccountAccountIdSessionKeysRoute
  '/account/$accountId/usage': typeof AuthenticatedAccountAccountIdUsageRoute
  '/session-key/$sessionKeyId/executions': typeof AuthenticatedSessionKeySessionKeyIdExecutionsRoute
  '/session-key/$sessionKeyId/overview': typeof AuthenticatedSessionKeySessionKeyIdOverviewRoute
  '/session-key/$sessionKeyId/policies': typeof AuthenticatedSessionKeySessionKeyIdPoliciesRoute
  '/settings/workspace/api-keys': typeof AuthenticatedSettingsWorkspaceApiKeysRoute
  '/settings/workspace/billings': typeof AuthenticatedSettingsWorkspaceBillingsRoute
  '/settings/workspace/cli-authorizations': typeof AuthenticatedSettingsWorkspaceCliAuthorizationsRoute
  '/settings/workspace/mcp': typeof AuthenticatedSettingsWorkspaceMcpRoute
  '/settings/workspace/members': typeof AuthenticatedSettingsWorkspaceMembersRoute
  '/account/$accountId/': typeof AuthenticatedAccountAccountIdIndexRoute
  '/session-key/$sessionKeyId/': typeof AuthenticatedSessionKeySessionKeyIdIndexRoute
  '/settings/workspace/': typeof AuthenticatedSettingsWorkspaceIndexRoute
}
export interface FileRoutesByTo {
  '/activity': typeof AuthenticatedActivityRoute
  '/identity': typeof AuthenticatedIdentityRoute
  '/inbox': typeof AuthenticatedInboxRoute
  '/mcp': typeof AuthenticatedMcpRoute
  '/templates': typeof AuthenticatedTemplatesRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthIndexRoute
  '/accounts/new': typeof AuthenticatedAccountsNewRoute
  '/cli/authorize': typeof AuthenticatedCliAuthorizeRoute
  '/execution/$executionId': typeof AuthenticatedExecutionExecutionIdRoute
  '/invitations/$invitationId': typeof AuthenticatedInvitationsInvitationIdRoute
  '/oauth/authorize': typeof AuthenticatedOauthAuthorizeRoute
  '/session-keys/new': typeof AuthenticatedSessionKeysNewRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/settings/security': typeof AuthenticatedSettingsSecurityRoute
  '/workspace/new': typeof AuthenticatedWorkspaceNewRoute
  '/accounts': typeof AuthenticatedAccountsIndexRoute
  '/session-keys': typeof AuthenticatedSessionKeysIndexRoute
  '/account/$accountId/assets': typeof AuthenticatedAccountAccountIdAssetsRoute
  '/account/$accountId/overview': typeof AuthenticatedAccountAccountIdOverviewRoute
  '/account/$accountId/session-keys': typeof AuthenticatedAccountAccountIdSessionKeysRoute
  '/account/$accountId/usage': typeof AuthenticatedAccountAccountIdUsageRoute
  '/session-key/$sessionKeyId/executions': typeof AuthenticatedSessionKeySessionKeyIdExecutionsRoute
  '/session-key/$sessionKeyId/overview': typeof AuthenticatedSessionKeySessionKeyIdOverviewRoute
  '/session-key/$sessionKeyId/policies': typeof AuthenticatedSessionKeySessionKeyIdPoliciesRoute
  '/settings/workspace/api-keys': typeof AuthenticatedSettingsWorkspaceApiKeysRoute
  '/settings/workspace/billings': typeof AuthenticatedSettingsWorkspaceBillingsRoute
  '/settings/workspace/cli-authorizations': typeof AuthenticatedSettingsWorkspaceCliAuthorizationsRoute
  '/settings/workspace/mcp': typeof AuthenticatedSettingsWorkspaceMcpRoute
  '/settings/workspace/members': typeof AuthenticatedSettingsWorkspaceMembersRoute
  '/account/$accountId': typeof AuthenticatedAccountAccountIdIndexRoute
  '/session-key/$sessionKeyId': typeof AuthenticatedSessionKeySessionKeyIdIndexRoute
  '/settings/workspace': typeof AuthenticatedSettingsWorkspaceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/_authenticated/activity': typeof AuthenticatedActivityRoute
  '/_authenticated/identity': typeof AuthenticatedIdentityRoute
  '/_authenticated/inbox': typeof AuthenticatedInboxRoute
  '/_authenticated/mcp': typeof AuthenticatedMcpRoute
  '/_authenticated/templates': typeof AuthenticatedTemplatesRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/_authenticated/account/$accountId': typeof AuthenticatedAccountAccountIdRouteRouteWithChildren
  '/_authenticated/session-key/$sessionKeyId': typeof AuthenticatedSessionKeySessionKeyIdRouteRouteWithChildren
  '/_authenticated/accounts/new': typeof AuthenticatedAccountsNewRoute
  '/_authenticated/cli/authorize': typeof AuthenticatedCliAuthorizeRoute
  '/_authenticated/execution/$executionId': typeof AuthenticatedExecutionExecutionIdRoute
  '/_authenticated/invitations/$invitationId': typeof AuthenticatedInvitationsInvitationIdRoute
  '/_authenticated/oauth/authorize': typeof AuthenticatedOauthAuthorizeRoute
  '/_authenticated/session-keys/new': typeof AuthenticatedSessionKeysNewRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/_authenticated/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/_authenticated/settings/security': typeof AuthenticatedSettingsSecurityRoute
  '/_authenticated/workspace/new': typeof AuthenticatedWorkspaceNewRoute
  '/_authenticated/accounts/': typeof AuthenticatedAccountsIndexRoute
  '/_authenticated/session-keys/': typeof AuthenticatedSessionKeysIndexRoute
  '/_authenticated/account/$accountId/assets': typeof AuthenticatedAccountAccountIdAssetsRoute
  '/_authenticated/account/$accountId/overview': typeof AuthenticatedAccountAccountIdOverviewRoute
  '/_authenticated/account/$accountId/session-keys': typeof AuthenticatedAccountAccountIdSessionKeysRoute
  '/_authenticated/account/$accountId/usage': typeof AuthenticatedAccountAccountIdUsageRoute
  '/_authenticated/session-key/$sessionKeyId/executions': typeof AuthenticatedSessionKeySessionKeyIdExecutionsRoute
  '/_authenticated/session-key/$sessionKeyId/overview': typeof AuthenticatedSessionKeySessionKeyIdOverviewRoute
  '/_authenticated/session-key/$sessionKeyId/policies': typeof AuthenticatedSessionKeySessionKeyIdPoliciesRoute
  '/_authenticated/settings/workspace/api-keys': typeof AuthenticatedSettingsWorkspaceApiKeysRoute
  '/_authenticated/settings/workspace/billings': typeof AuthenticatedSettingsWorkspaceBillingsRoute
  '/_authenticated/settings/workspace/cli-authorizations': typeof AuthenticatedSettingsWorkspaceCliAuthorizationsRoute
  '/_authenticated/settings/workspace/mcp': typeof AuthenticatedSettingsWorkspaceMcpRoute
  '/_authenticated/settings/workspace/members': typeof AuthenticatedSettingsWorkspaceMembersRoute
  '/_authenticated/account/$accountId/': typeof AuthenticatedAccountAccountIdIndexRoute
  '/_authenticated/session-key/$sessionKeyId/': typeof AuthenticatedSessionKeySessionKeyIdIndexRoute
  '/_authenticated/settings/workspace/': typeof AuthenticatedSettingsWorkspaceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/activity'
    | '/identity'
    | '/inbox'
    | '/mcp'
    | '/templates'
    | '/auth/verify'
    | '/auth/'
    | '/account/$accountId'
    | '/session-key/$sessionKeyId'
    | '/accounts/new'
    | '/cli/authorize'
    | '/execution/$executionId'
    | '/invitations/$invitationId'
    | '/oauth/authorize'
    | '/session-keys/new'
    | '/settings/notifications'
    | '/settings/profile'
    | '/settings/security'
    | '/workspace/new'
    | '/accounts/'
    | '/session-keys/'
    | '/account/$accountId/assets'
    | '/account/$accountId/overview'
    | '/account/$accountId/session-keys'
    | '/account/$accountId/usage'
    | '/session-key/$sessionKeyId/executions'
    | '/session-key/$sessionKeyId/overview'
    | '/session-key/$sessionKeyId/policies'
    | '/settings/workspace/api-keys'
    | '/settings/workspace/billings'
    | '/settings/workspace/cli-authorizations'
    | '/settings/workspace/mcp'
    | '/settings/workspace/members'
    | '/account/$accountId/'
    | '/session-key/$sessionKeyId/'
    | '/settings/workspace/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/activity'
    | '/identity'
    | '/inbox'
    | '/mcp'
    | '/templates'
    | '/auth/verify'
    | '/'
    | '/auth'
    | '/accounts/new'
    | '/cli/authorize'
    | '/execution/$executionId'
    | '/invitations/$invitationId'
    | '/oauth/authorize'
    | '/session-keys/new'
    | '/settings/notifications'
    | '/settings/profile'
    | '/settings/security'
    | '/workspace/new'
    | '/accounts'
    | '/session-keys'
    | '/account/$accountId/assets'
    | '/account/$accountId/overview'
    | '/account/$accountId/session-keys'
    | '/account/$accountId/usage'
    | '/session-key/$sessionKeyId/executions'
    | '/session-key/$sessionKeyId/overview'
    | '/session-key/$sessionKeyId/policies'
    | '/settings/workspace/api-keys'
    | '/settings/workspace/billings'
    | '/settings/workspace/cli-authorizations'
    | '/settings/workspace/mcp'
    | '/settings/workspace/members'
    | '/account/$accountId'
    | '/session-key/$sessionKeyId'
    | '/settings/workspace'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/activity'
    | '/_authenticated/identity'
    | '/_authenticated/inbox'
    | '/_authenticated/mcp'
    | '/_authenticated/templates'
    | '/auth/verify'
    | '/_authenticated/'
    | '/auth/'
    | '/_authenticated/account/$accountId'
    | '/_authenticated/session-key/$sessionKeyId'
    | '/_authenticated/accounts/new'
    | '/_authenticated/cli/authorize'
    | '/_authenticated/execution/$executionId'
    | '/_authenticated/invitations/$invitationId'
    | '/_authenticated/oauth/authorize'
    | '/_authenticated/session-keys/new'
    | '/_authenticated/settings/notifications'
    | '/_authenticated/settings/profile'
    | '/_authenticated/settings/security'
    | '/_authenticated/workspace/new'
    | '/_authenticated/accounts/'
    | '/_authenticated/session-keys/'
    | '/_authenticated/account/$accountId/assets'
    | '/_authenticated/account/$accountId/overview'
    | '/_authenticated/account/$accountId/session-keys'
    | '/_authenticated/account/$accountId/usage'
    | '/_authenticated/session-key/$sessionKeyId/executions'
    | '/_authenticated/session-key/$sessionKeyId/overview'
    | '/_authenticated/session-key/$sessionKeyId/policies'
    | '/_authenticated/settings/workspace/api-keys'
    | '/_authenticated/settings/workspace/billings'
    | '/_authenticated/settings/workspace/cli-authorizations'
    | '/_authenticated/settings/workspace/mcp'
    | '/_authenticated/settings/workspace/members'
    | '/_authenticated/account/$accountId/'
    | '/_authenticated/session-key/$sessionKeyId/'
    | '/_authenticated/settings/workspace/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/activity': {
      id: '/_authenticated/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AuthenticatedActivityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/identity': {
      id: '/_authenticated/identity'
      path: '/identity'
      fullPath: '/identity'
      preLoaderRoute: typeof AuthenticatedIdentityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inbox': {
      id: '/_authenticated/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AuthenticatedInboxRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mcp': {
      id: '/_authenticated/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof AuthenticatedMcpRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/templates': {
      id: '/_authenticated/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof AuthenticatedTemplatesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/auth/': {
      id: '/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/verify': {
      id: '/auth/verify'
      path: '/verify'
      fullPath: '/auth/verify'
      preLoaderRoute: typeof AuthVerifyRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_authenticated/account/$accountId': {
      id: '/_authenticated/account/$accountId'
      path: '/account/$accountId'
      fullPath: '/account/$accountId'
      preLoaderRoute: typeof AuthenticatedAccountAccountIdRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/accounts/': {
      id: '/_authenticated/accounts/'
      path: '/accounts'
      fullPath: '/accounts/'
      preLoaderRoute: typeof AuthenticatedAccountsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/accounts/new': {
      id: '/_authenticated/accounts/new'
      path: '/accounts/new'
      fullPath: '/accounts/new'
      preLoaderRoute: typeof AuthenticatedAccountsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cli/authorize': {
      id: '/_authenticated/cli/authorize'
      path: '/cli/authorize'
      fullPath: '/cli/authorize'
      preLoaderRoute: typeof AuthenticatedCliAuthorizeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/execution/$executionId': {
      id: '/_authenticated/execution/$executionId'
      path: '/execution/$executionId'
      fullPath: '/execution/$executionId'
      preLoaderRoute: typeof AuthenticatedExecutionExecutionIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/invitations/$invitationId': {
      id: '/_authenticated/invitations/$invitationId'
      path: '/invitations/$invitationId'
      fullPath: '/invitations/$invitationId'
      preLoaderRoute: typeof AuthenticatedInvitationsInvitationIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/oauth/authorize': {
      id: '/_authenticated/oauth/authorize'
      path: '/oauth/authorize'
      fullPath: '/oauth/authorize'
      preLoaderRoute: typeof AuthenticatedOauthAuthorizeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/session-key/$sessionKeyId': {
      id: '/_authenticated/session-key/$sessionKeyId'
      path: '/session-key/$sessionKeyId'
      fullPath: '/session-key/$sessionKeyId'
      preLoaderRoute: typeof AuthenticatedSessionKeySessionKeyIdRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/session-keys/': {
      id: '/_authenticated/session-keys/'
      path: '/session-keys'
      fullPath: '/session-keys/'
      preLoaderRoute: typeof AuthenticatedSessionKeysIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/session-keys/new': {
      id: '/_authenticated/session-keys/new'
      path: '/session-keys/new'
      fullPath: '/session-keys/new'
      preLoaderRoute: typeof AuthenticatedSessionKeysNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/settings/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/profile': {
      id: '/_authenticated/settings/profile'
      path: '/settings/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof AuthenticatedSettingsProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/security': {
      id: '/_authenticated/settings/security'
      path: '/settings/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof AuthenticatedSettingsSecurityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/workspace/new': {
      id: '/_authenticated/workspace/new'
      path: '/workspace/new'
      fullPath: '/workspace/new'
      preLoaderRoute: typeof AuthenticatedWorkspaceNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/account/$accountId/': {
      id: '/_authenticated/account/$accountId/'
      path: '/'
      fullPath: '/account/$accountId/'
      preLoaderRoute: typeof AuthenticatedAccountAccountIdIndexRouteImport
      parentRoute: typeof AuthenticatedAccountAccountIdRouteRoute
    }
    '/_authenticated/account/$accountId/assets': {
      id: '/_authenticated/account/$accountId/assets'
      path: '/assets'
      fullPath: '/account/$accountId/assets'
      preLoaderRoute: typeof AuthenticatedAccountAccountIdAssetsRouteImport
      parentRoute: typeof AuthenticatedAccountAccountIdRouteRoute
    }
    '/_authenticated/account/$accountId/overview': {
      id: '/_authenticated/account/$accountId/overview'
      path: '/overview'
      fullPath: '/account/$accountId/overview'
      preLoaderRoute: typeof AuthenticatedAccountAccountIdOverviewRouteImport
      parentRoute: typeof AuthenticatedAccountAccountIdRouteRoute
    }
    '/_authenticated/account/$accountId/session-keys': {
      id: '/_authenticated/account/$accountId/session-keys'
      path: '/session-keys'
      fullPath: '/account/$accountId/session-keys'
      preLoaderRoute: typeof AuthenticatedAccountAccountIdSessionKeysRouteImport
      parentRoute: typeof AuthenticatedAccountAccountIdRouteRoute
    }
    '/_authenticated/account/$accountId/usage': {
      id: '/_authenticated/account/$accountId/usage'
      path: '/usage'
      fullPath: '/account/$accountId/usage'
      preLoaderRoute: typeof AuthenticatedAccountAccountIdUsageRouteImport
      parentRoute: typeof AuthenticatedAccountAccountIdRouteRoute
    }
    '/_authenticated/session-key/$sessionKeyId/': {
      id: '/_authenticated/session-key/$sessionKeyId/'
      path: '/'
      fullPath: '/session-key/$sessionKeyId/'
      preLoaderRoute: typeof AuthenticatedSessionKeySessionKeyIdIndexRouteImport
      parentRoute: typeof AuthenticatedSessionKeySessionKeyIdRouteRoute
    }
    '/_authenticated/session-key/$sessionKeyId/executions': {
      id: '/_authenticated/session-key/$sessionKeyId/executions'
      path: '/executions'
      fullPath: '/session-key/$sessionKeyId/executions'
      preLoaderRoute: typeof AuthenticatedSessionKeySessionKeyIdExecutionsRouteImport
      parentRoute: typeof AuthenticatedSessionKeySessionKeyIdRouteRoute
    }
    '/_authenticated/session-key/$sessionKeyId/overview': {
      id: '/_authenticated/session-key/$sessionKeyId/overview'
      path: '/overview'
      fullPath: '/session-key/$sessionKeyId/overview'
      preLoaderRoute: typeof AuthenticatedSessionKeySessionKeyIdOverviewRouteImport
      parentRoute: typeof AuthenticatedSessionKeySessionKeyIdRouteRoute
    }
    '/_authenticated/session-key/$sessionKeyId/policies': {
      id: '/_authenticated/session-key/$sessionKeyId/policies'
      path: '/policies'
      fullPath: '/session-key/$sessionKeyId/policies'
      preLoaderRoute: typeof AuthenticatedSessionKeySessionKeyIdPoliciesRouteImport
      parentRoute: typeof AuthenticatedSessionKeySessionKeyIdRouteRoute
    }
    '/_authenticated/settings/workspace/': {
      id: '/_authenticated/settings/workspace/'
      path: '/settings/workspace'
      fullPath: '/settings/workspace/'
      preLoaderRoute: typeof AuthenticatedSettingsWorkspaceIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/workspace/api-keys': {
      id: '/_authenticated/settings/workspace/api-keys'
      path: '/settings/workspace/api-keys'
      fullPath: '/settings/workspace/api-keys'
      preLoaderRoute: typeof AuthenticatedSettingsWorkspaceApiKeysRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/workspace/billings': {
      id: '/_authenticated/settings/workspace/billings'
      path: '/settings/workspace/billings'
      fullPath: '/settings/workspace/billings'
      preLoaderRoute: typeof AuthenticatedSettingsWorkspaceBillingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/workspace/cli-authorizations': {
      id: '/_authenticated/settings/workspace/cli-authorizations'
      path: '/settings/workspace/cli-authorizations'
      fullPath: '/settings/workspace/cli-authorizations'
      preLoaderRoute: typeof AuthenticatedSettingsWorkspaceCliAuthorizationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/workspace/mcp': {
      id: '/_authenticated/settings/workspace/mcp'
      path: '/settings/workspace/mcp'
      fullPath: '/settings/workspace/mcp'
      preLoaderRoute: typeof AuthenticatedSettingsWorkspaceMcpRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/workspace/members': {
      id: '/_authenticated/settings/workspace/members'
      path: '/settings/workspace/members'
      fullPath: '/settings/workspace/members'
      preLoaderRoute: typeof AuthenticatedSettingsWorkspaceMembersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedAccountAccountIdRouteRouteChildren {
  AuthenticatedAccountAccountIdAssetsRoute: typeof AuthenticatedAccountAccountIdAssetsRoute
  AuthenticatedAccountAccountIdOverviewRoute: typeof AuthenticatedAccountAccountIdOverviewRoute
  AuthenticatedAccountAccountIdSessionKeysRoute: typeof AuthenticatedAccountAccountIdSessionKeysRoute
  AuthenticatedAccountAccountIdUsageRoute: typeof AuthenticatedAccountAccountIdUsageRoute
  AuthenticatedAccountAccountIdIndexRoute: typeof AuthenticatedAccountAccountIdIndexRoute
}

const AuthenticatedAccountAccountIdRouteRouteChildren: AuthenticatedAccountAccountIdRouteRouteChildren =
  {
    AuthenticatedAccountAccountIdAssetsRoute:
      AuthenticatedAccountAccountIdAssetsRoute,
    AuthenticatedAccountAccountIdOverviewRoute:
      AuthenticatedAccountAccountIdOverviewRoute,
    AuthenticatedAccountAccountIdSessionKeysRoute:
      AuthenticatedAccountAccountIdSessionKeysRoute,
    AuthenticatedAccountAccountIdUsageRoute:
      AuthenticatedAccountAccountIdUsageRoute,
    AuthenticatedAccountAccountIdIndexRoute:
      AuthenticatedAccountAccountIdIndexRoute,
  }

const AuthenticatedAccountAccountIdRouteRouteWithChildren =
  AuthenticatedAccountAccountIdRouteRoute._addFileChildren(
    AuthenticatedAccountAccountIdRouteRouteChildren,
  )

interface AuthenticatedSessionKeySessionKeyIdRouteRouteChildren {
  AuthenticatedSessionKeySessionKeyIdExecutionsRoute: typeof AuthenticatedSessionKeySessionKeyIdExecutionsRoute
  AuthenticatedSessionKeySessionKeyIdOverviewRoute: typeof AuthenticatedSessionKeySessionKeyIdOverviewRoute
  AuthenticatedSessionKeySessionKeyIdPoliciesRoute: typeof AuthenticatedSessionKeySessionKeyIdPoliciesRoute
  AuthenticatedSessionKeySessionKeyIdIndexRoute: typeof AuthenticatedSessionKeySessionKeyIdIndexRoute
}

const AuthenticatedSessionKeySessionKeyIdRouteRouteChildren: AuthenticatedSessionKeySessionKeyIdRouteRouteChildren =
  {
    AuthenticatedSessionKeySessionKeyIdExecutionsRoute:
      AuthenticatedSessionKeySessionKeyIdExecutionsRoute,
    AuthenticatedSessionKeySessionKeyIdOverviewRoute:
      AuthenticatedSessionKeySessionKeyIdOverviewRoute,
    AuthenticatedSessionKeySessionKeyIdPoliciesRoute:
      AuthenticatedSessionKeySessionKeyIdPoliciesRoute,
    AuthenticatedSessionKeySessionKeyIdIndexRoute:
      AuthenticatedSessionKeySessionKeyIdIndexRoute,
  }

const AuthenticatedSessionKeySessionKeyIdRouteRouteWithChildren =
  AuthenticatedSessionKeySessionKeyIdRouteRoute._addFileChildren(
    AuthenticatedSessionKeySessionKeyIdRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedActivityRoute: typeof AuthenticatedActivityRoute
  AuthenticatedIdentityRoute: typeof AuthenticatedIdentityRoute
  AuthenticatedInboxRoute: typeof AuthenticatedInboxRoute
  AuthenticatedMcpRoute: typeof AuthenticatedMcpRoute
  AuthenticatedTemplatesRoute: typeof AuthenticatedTemplatesRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAccountAccountIdRouteRoute: typeof AuthenticatedAccountAccountIdRouteRouteWithChildren
  AuthenticatedSessionKeySessionKeyIdRouteRoute: typeof AuthenticatedSessionKeySessionKeyIdRouteRouteWithChildren
  AuthenticatedAccountsNewRoute: typeof AuthenticatedAccountsNewRoute
  AuthenticatedCliAuthorizeRoute: typeof AuthenticatedCliAuthorizeRoute
  AuthenticatedExecutionExecutionIdRoute: typeof AuthenticatedExecutionExecutionIdRoute
  AuthenticatedInvitationsInvitationIdRoute: typeof AuthenticatedInvitationsInvitationIdRoute
  AuthenticatedOauthAuthorizeRoute: typeof AuthenticatedOauthAuthorizeRoute
  AuthenticatedSessionKeysNewRoute: typeof AuthenticatedSessionKeysNewRoute
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRoute
  AuthenticatedSettingsProfileRoute: typeof AuthenticatedSettingsProfileRoute
  AuthenticatedSettingsSecurityRoute: typeof AuthenticatedSettingsSecurityRoute
  AuthenticatedWorkspaceNewRoute: typeof AuthenticatedWorkspaceNewRoute
  AuthenticatedAccountsIndexRoute: typeof AuthenticatedAccountsIndexRoute
  AuthenticatedSessionKeysIndexRoute: typeof AuthenticatedSessionKeysIndexRoute
  AuthenticatedSettingsWorkspaceApiKeysRoute: typeof AuthenticatedSettingsWorkspaceApiKeysRoute
  AuthenticatedSettingsWorkspaceBillingsRoute: typeof AuthenticatedSettingsWorkspaceBillingsRoute
  AuthenticatedSettingsWorkspaceCliAuthorizationsRoute: typeof AuthenticatedSettingsWorkspaceCliAuthorizationsRoute
  AuthenticatedSettingsWorkspaceMcpRoute: typeof AuthenticatedSettingsWorkspaceMcpRoute
  AuthenticatedSettingsWorkspaceMembersRoute: typeof AuthenticatedSettingsWorkspaceMembersRoute
  AuthenticatedSettingsWorkspaceIndexRoute: typeof AuthenticatedSettingsWorkspaceIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedActivityRoute: AuthenticatedActivityRoute,
  AuthenticatedIdentityRoute: AuthenticatedIdentityRoute,
  AuthenticatedInboxRoute: AuthenticatedInboxRoute,
  AuthenticatedMcpRoute: AuthenticatedMcpRoute,
  AuthenticatedTemplatesRoute: AuthenticatedTemplatesRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAccountAccountIdRouteRoute:
    AuthenticatedAccountAccountIdRouteRouteWithChildren,
  AuthenticatedSessionKeySessionKeyIdRouteRoute:
    AuthenticatedSessionKeySessionKeyIdRouteRouteWithChildren,
  AuthenticatedAccountsNewRoute: AuthenticatedAccountsNewRoute,
  AuthenticatedCliAuthorizeRoute: AuthenticatedCliAuthorizeRoute,
  AuthenticatedExecutionExecutionIdRoute:
    AuthenticatedExecutionExecutionIdRoute,
  AuthenticatedInvitationsInvitationIdRoute:
    AuthenticatedInvitationsInvitationIdRoute,
  AuthenticatedOauthAuthorizeRoute: AuthenticatedOauthAuthorizeRoute,
  AuthenticatedSessionKeysNewRoute: AuthenticatedSessionKeysNewRoute,
  AuthenticatedSettingsNotificationsRoute:
    AuthenticatedSettingsNotificationsRoute,
  AuthenticatedSettingsProfileRoute: AuthenticatedSettingsProfileRoute,
  AuthenticatedSettingsSecurityRoute: AuthenticatedSettingsSecurityRoute,
  AuthenticatedWorkspaceNewRoute: AuthenticatedWorkspaceNewRoute,
  AuthenticatedAccountsIndexRoute: AuthenticatedAccountsIndexRoute,
  AuthenticatedSessionKeysIndexRoute: AuthenticatedSessionKeysIndexRoute,
  AuthenticatedSettingsWorkspaceApiKeysRoute:
    AuthenticatedSettingsWorkspaceApiKeysRoute,
  AuthenticatedSettingsWorkspaceBillingsRoute:
    AuthenticatedSettingsWorkspaceBillingsRoute,
  AuthenticatedSettingsWorkspaceCliAuthorizationsRoute:
    AuthenticatedSettingsWorkspaceCliAuthorizationsRoute,
  AuthenticatedSettingsWorkspaceMcpRoute:
    AuthenticatedSettingsWorkspaceMcpRoute,
  AuthenticatedSettingsWorkspaceMembersRoute:
    AuthenticatedSettingsWorkspaceMembersRoute,
  AuthenticatedSettingsWorkspaceIndexRoute:
    AuthenticatedSettingsWorkspaceIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteRouteChildren {
  AuthVerifyRoute: typeof AuthVerifyRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthVerifyRoute: AuthVerifyRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
