/** biome-ignore-all lint/style/useNamingConvention: safe */

/** biome-ignore-all lint/suspicious/noExplicitAny: safe  */

// @ts-nocheck

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./app/__root";
import { Route as DashboardRouteRouteImport } from "./app/dashboard/route";
import { Route as IndexRouteImport } from "./app/index";
import { Route as AuthIndexRouteImport } from "./app/auth/index";
import { Route as DashboardSettingsIndexRouteImport } from "./app/dashboard/settings/index";
import { Route as DashboardprimaryIndexRouteImport } from "./app/dashboard/(primary)/index";
import { Route as DashboardSettingsSecurityIndexRouteImport } from "./app/dashboard/settings/security/index";
import { Route as DashboardSettingsProfileIndexRouteImport } from "./app/dashboard/settings/profile/index";
import { Route as DashboardSettingsNotificationsIndexRouteImport } from "./app/dashboard/settings/notifications/index";
import { Route as DashboardprimaryInboxIndexRouteImport } from "./app/dashboard/(primary)/inbox/index";
import { Route as DashboardprimaryAssetsIndexRouteImport } from "./app/dashboard/(primary)/assets/index";
import { Route as DashboardcoreTemplatesIndexRouteImport } from "./app/dashboard/(core)/templates/index";
import { Route as DashboardcoreSessionKeysIndexRouteImport } from "./app/dashboard/(core)/session-keys/index";
import { Route as DashboardcoreActivityIndexRouteImport } from "./app/dashboard/(core)/activity/index";
import { Route as DashboardcoreAccountsIndexRouteImport } from "./app/dashboard/(core)/accounts/index";
import { Route as DashboardagentsMcpIndexRouteImport } from "./app/dashboard/(agents)/mcp/index";
import { Route as DashboardagentsIdentityIndexRouteImport } from "./app/dashboard/(agents)/identity/index";
import { Route as DashboardcoreSessionKeysCreateIndexRouteImport } from "./app/dashboard/(core)/session-keys/create/index";
import { Route as DashboardcoreAccountsNewIndexRouteImport } from "./app/dashboard/(core)/accounts/new/index";

const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: "/dashboard",
  path: "/dashboard",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: "/auth/",
  path: "/auth/",
  getParentRoute: () => rootRouteImport,
} as any);
const DashboardSettingsIndexRoute = DashboardSettingsIndexRouteImport.update({
  id: "/settings/",
  path: "/settings/",
  getParentRoute: () => DashboardRouteRoute,
} as any);
const DashboardprimaryIndexRoute = DashboardprimaryIndexRouteImport.update({
  id: "/(primary)/",
  path: "/",
  getParentRoute: () => DashboardRouteRoute,
} as any);
const DashboardSettingsSecurityIndexRoute =
  DashboardSettingsSecurityIndexRouteImport.update({
    id: "/settings/security/",
    path: "/settings/security/",
    getParentRoute: () => DashboardRouteRoute,
  } as any);
const DashboardSettingsProfileIndexRoute =
  DashboardSettingsProfileIndexRouteImport.update({
    id: "/settings/profile/",
    path: "/settings/profile/",
    getParentRoute: () => DashboardRouteRoute,
  } as any);
const DashboardSettingsNotificationsIndexRoute =
  DashboardSettingsNotificationsIndexRouteImport.update({
    id: "/settings/notifications/",
    path: "/settings/notifications/",
    getParentRoute: () => DashboardRouteRoute,
  } as any);
const DashboardprimaryInboxIndexRoute =
  DashboardprimaryInboxIndexRouteImport.update({
    id: "/(primary)/inbox/",
    path: "/inbox/",
    getParentRoute: () => DashboardRouteRoute,
  } as any);
const DashboardprimaryAssetsIndexRoute =
  DashboardprimaryAssetsIndexRouteImport.update({
    id: "/(primary)/assets/",
    path: "/assets/",
    getParentRoute: () => DashboardRouteRoute,
  } as any);
const DashboardcoreTemplatesIndexRoute =
  DashboardcoreTemplatesIndexRouteImport.update({
    id: "/(core)/templates/",
    path: "/templates/",
    getParentRoute: () => DashboardRouteRoute,
  } as any);
const DashboardcoreSessionKeysIndexRoute =
  DashboardcoreSessionKeysIndexRouteImport.update({
    id: "/(core)/session-keys/",
    path: "/session-keys/",
    getParentRoute: () => DashboardRouteRoute,
  } as any);
const DashboardcoreActivityIndexRoute =
  DashboardcoreActivityIndexRouteImport.update({
    id: "/(core)/activity/",
    path: "/activity/",
    getParentRoute: () => DashboardRouteRoute,
  } as any);
const DashboardcoreAccountsIndexRoute =
  DashboardcoreAccountsIndexRouteImport.update({
    id: "/(core)/accounts/",
    path: "/accounts/",
    getParentRoute: () => DashboardRouteRoute,
  } as any);
const DashboardagentsMcpIndexRoute = DashboardagentsMcpIndexRouteImport.update({
  id: "/(agents)/mcp/",
  path: "/mcp/",
  getParentRoute: () => DashboardRouteRoute,
} as any);
const DashboardagentsIdentityIndexRoute =
  DashboardagentsIdentityIndexRouteImport.update({
    id: "/(agents)/identity/",
    path: "/identity/",
    getParentRoute: () => DashboardRouteRoute,
  } as any);
const DashboardcoreSessionKeysCreateIndexRoute =
  DashboardcoreSessionKeysCreateIndexRouteImport.update({
    id: "/(core)/session-keys/create/",
    path: "/session-keys/create/",
    getParentRoute: () => DashboardRouteRoute,
  } as any);
const DashboardcoreAccountsNewIndexRoute =
  DashboardcoreAccountsNewIndexRouteImport.update({
    id: "/(core)/accounts/new/",
    path: "/accounts/new/",
    getParentRoute: () => DashboardRouteRoute,
  } as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/dashboard": typeof DashboardRouteRouteWithChildren;
  "/auth/": typeof AuthIndexRoute;
  "/dashboard/": typeof DashboardprimaryIndexRoute;
  "/dashboard/settings/": typeof DashboardSettingsIndexRoute;
  "/dashboard/identity/": typeof DashboardagentsIdentityIndexRoute;
  "/dashboard/mcp/": typeof DashboardagentsMcpIndexRoute;
  "/dashboard/accounts/": typeof DashboardcoreAccountsIndexRoute;
  "/dashboard/activity/": typeof DashboardcoreActivityIndexRoute;
  "/dashboard/session-keys/": typeof DashboardcoreSessionKeysIndexRoute;
  "/dashboard/templates/": typeof DashboardcoreTemplatesIndexRoute;
  "/dashboard/assets/": typeof DashboardprimaryAssetsIndexRoute;
  "/dashboard/inbox/": typeof DashboardprimaryInboxIndexRoute;
  "/dashboard/settings/notifications/": typeof DashboardSettingsNotificationsIndexRoute;
  "/dashboard/settings/profile/": typeof DashboardSettingsProfileIndexRoute;
  "/dashboard/settings/security/": typeof DashboardSettingsSecurityIndexRoute;
  "/dashboard/accounts/new/": typeof DashboardcoreAccountsNewIndexRoute;
  "/dashboard/session-keys/create/": typeof DashboardcoreSessionKeysCreateIndexRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/auth": typeof AuthIndexRoute;
  "/dashboard": typeof DashboardprimaryIndexRoute;
  "/dashboard/settings": typeof DashboardSettingsIndexRoute;
  "/dashboard/identity": typeof DashboardagentsIdentityIndexRoute;
  "/dashboard/mcp": typeof DashboardagentsMcpIndexRoute;
  "/dashboard/accounts": typeof DashboardcoreAccountsIndexRoute;
  "/dashboard/activity": typeof DashboardcoreActivityIndexRoute;
  "/dashboard/session-keys": typeof DashboardcoreSessionKeysIndexRoute;
  "/dashboard/templates": typeof DashboardcoreTemplatesIndexRoute;
  "/dashboard/assets": typeof DashboardprimaryAssetsIndexRoute;
  "/dashboard/inbox": typeof DashboardprimaryInboxIndexRoute;
  "/dashboard/settings/notifications": typeof DashboardSettingsNotificationsIndexRoute;
  "/dashboard/settings/profile": typeof DashboardSettingsProfileIndexRoute;
  "/dashboard/settings/security": typeof DashboardSettingsSecurityIndexRoute;
  "/dashboard/accounts/new": typeof DashboardcoreAccountsNewIndexRoute;
  "/dashboard/session-keys/create": typeof DashboardcoreSessionKeysCreateIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/dashboard": typeof DashboardRouteRouteWithChildren;
  "/auth/": typeof AuthIndexRoute;
  "/dashboard/(primary)/": typeof DashboardprimaryIndexRoute;
  "/dashboard/settings/": typeof DashboardSettingsIndexRoute;
  "/dashboard/(agents)/identity/": typeof DashboardagentsIdentityIndexRoute;
  "/dashboard/(agents)/mcp/": typeof DashboardagentsMcpIndexRoute;
  "/dashboard/(core)/accounts/": typeof DashboardcoreAccountsIndexRoute;
  "/dashboard/(core)/activity/": typeof DashboardcoreActivityIndexRoute;
  "/dashboard/(core)/session-keys/": typeof DashboardcoreSessionKeysIndexRoute;
  "/dashboard/(core)/templates/": typeof DashboardcoreTemplatesIndexRoute;
  "/dashboard/(primary)/assets/": typeof DashboardprimaryAssetsIndexRoute;
  "/dashboard/(primary)/inbox/": typeof DashboardprimaryInboxIndexRoute;
  "/dashboard/settings/notifications/": typeof DashboardSettingsNotificationsIndexRoute;
  "/dashboard/settings/profile/": typeof DashboardSettingsProfileIndexRoute;
  "/dashboard/settings/security/": typeof DashboardSettingsSecurityIndexRoute;
  "/dashboard/(core)/accounts/new/": typeof DashboardcoreAccountsNewIndexRoute;
  "/dashboard/(core)/session-keys/create/": typeof DashboardcoreSessionKeysCreateIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/dashboard"
    | "/auth/"
    | "/dashboard/"
    | "/dashboard/settings/"
    | "/dashboard/identity/"
    | "/dashboard/mcp/"
    | "/dashboard/accounts/"
    | "/dashboard/activity/"
    | "/dashboard/session-keys/"
    | "/dashboard/templates/"
    | "/dashboard/assets/"
    | "/dashboard/inbox/"
    | "/dashboard/settings/notifications/"
    | "/dashboard/settings/profile/"
    | "/dashboard/settings/security/"
    | "/dashboard/accounts/new/"
    | "/dashboard/session-keys/create/";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/auth"
    | "/dashboard"
    | "/dashboard/settings"
    | "/dashboard/identity"
    | "/dashboard/mcp"
    | "/dashboard/accounts"
    | "/dashboard/activity"
    | "/dashboard/session-keys"
    | "/dashboard/templates"
    | "/dashboard/assets"
    | "/dashboard/inbox"
    | "/dashboard/settings/notifications"
    | "/dashboard/settings/profile"
    | "/dashboard/settings/security"
    | "/dashboard/accounts/new"
    | "/dashboard/session-keys/create";
  id:
    | "__root__"
    | "/"
    | "/dashboard"
    | "/auth/"
    | "/dashboard/(primary)/"
    | "/dashboard/settings/"
    | "/dashboard/(agents)/identity/"
    | "/dashboard/(agents)/mcp/"
    | "/dashboard/(core)/accounts/"
    | "/dashboard/(core)/activity/"
    | "/dashboard/(core)/session-keys/"
    | "/dashboard/(core)/templates/"
    | "/dashboard/(primary)/assets/"
    | "/dashboard/(primary)/inbox/"
    | "/dashboard/settings/notifications/"
    | "/dashboard/settings/profile/"
    | "/dashboard/settings/security/"
    | "/dashboard/(core)/accounts/new/"
    | "/dashboard/(core)/session-keys/create/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren;
  AuthIndexRoute: typeof AuthIndexRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/dashboard": {
      id: "/dashboard";
      path: "/dashboard";
      fullPath: "/dashboard";
      preLoaderRoute: typeof DashboardRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/auth/": {
      id: "/auth/";
      path: "/auth";
      fullPath: "/auth/";
      preLoaderRoute: typeof AuthIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/dashboard/settings/": {
      id: "/dashboard/settings/";
      path: "/settings";
      fullPath: "/dashboard/settings/";
      preLoaderRoute: typeof DashboardSettingsIndexRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    "/dashboard/(primary)/": {
      id: "/dashboard/(primary)/";
      path: "/";
      fullPath: "/dashboard/";
      preLoaderRoute: typeof DashboardprimaryIndexRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    "/dashboard/settings/security/": {
      id: "/dashboard/settings/security/";
      path: "/settings/security";
      fullPath: "/dashboard/settings/security/";
      preLoaderRoute: typeof DashboardSettingsSecurityIndexRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    "/dashboard/settings/profile/": {
      id: "/dashboard/settings/profile/";
      path: "/settings/profile";
      fullPath: "/dashboard/settings/profile/";
      preLoaderRoute: typeof DashboardSettingsProfileIndexRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    "/dashboard/settings/notifications/": {
      id: "/dashboard/settings/notifications/";
      path: "/settings/notifications";
      fullPath: "/dashboard/settings/notifications/";
      preLoaderRoute: typeof DashboardSettingsNotificationsIndexRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    "/dashboard/(primary)/inbox/": {
      id: "/dashboard/(primary)/inbox/";
      path: "/inbox";
      fullPath: "/dashboard/inbox/";
      preLoaderRoute: typeof DashboardprimaryInboxIndexRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    "/dashboard/(primary)/assets/": {
      id: "/dashboard/(primary)/assets/";
      path: "/assets";
      fullPath: "/dashboard/assets/";
      preLoaderRoute: typeof DashboardprimaryAssetsIndexRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    "/dashboard/(core)/templates/": {
      id: "/dashboard/(core)/templates/";
      path: "/templates";
      fullPath: "/dashboard/templates/";
      preLoaderRoute: typeof DashboardcoreTemplatesIndexRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    "/dashboard/(core)/session-keys/": {
      id: "/dashboard/(core)/session-keys/";
      path: "/session-keys";
      fullPath: "/dashboard/session-keys/";
      preLoaderRoute: typeof DashboardcoreSessionKeysIndexRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    "/dashboard/(core)/activity/": {
      id: "/dashboard/(core)/activity/";
      path: "/activity";
      fullPath: "/dashboard/activity/";
      preLoaderRoute: typeof DashboardcoreActivityIndexRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    "/dashboard/(core)/accounts/": {
      id: "/dashboard/(core)/accounts/";
      path: "/accounts";
      fullPath: "/dashboard/accounts/";
      preLoaderRoute: typeof DashboardcoreAccountsIndexRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    "/dashboard/(agents)/mcp/": {
      id: "/dashboard/(agents)/mcp/";
      path: "/mcp";
      fullPath: "/dashboard/mcp/";
      preLoaderRoute: typeof DashboardagentsMcpIndexRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    "/dashboard/(agents)/identity/": {
      id: "/dashboard/(agents)/identity/";
      path: "/identity";
      fullPath: "/dashboard/identity/";
      preLoaderRoute: typeof DashboardagentsIdentityIndexRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    "/dashboard/(core)/session-keys/create/": {
      id: "/dashboard/(core)/session-keys/create/";
      path: "/session-keys/create";
      fullPath: "/dashboard/session-keys/create/";
      preLoaderRoute: typeof DashboardcoreSessionKeysCreateIndexRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    "/dashboard/(core)/accounts/new/": {
      id: "/dashboard/(core)/accounts/new/";
      path: "/accounts/new";
      fullPath: "/dashboard/accounts/new/";
      preLoaderRoute: typeof DashboardcoreAccountsNewIndexRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
  }
}

interface DashboardRouteRouteChildren {
  DashboardprimaryIndexRoute: typeof DashboardprimaryIndexRoute;
  DashboardSettingsIndexRoute: typeof DashboardSettingsIndexRoute;
  DashboardagentsIdentityIndexRoute: typeof DashboardagentsIdentityIndexRoute;
  DashboardagentsMcpIndexRoute: typeof DashboardagentsMcpIndexRoute;
  DashboardcoreAccountsIndexRoute: typeof DashboardcoreAccountsIndexRoute;
  DashboardcoreActivityIndexRoute: typeof DashboardcoreActivityIndexRoute;
  DashboardcoreSessionKeysIndexRoute: typeof DashboardcoreSessionKeysIndexRoute;
  DashboardcoreTemplatesIndexRoute: typeof DashboardcoreTemplatesIndexRoute;
  DashboardprimaryAssetsIndexRoute: typeof DashboardprimaryAssetsIndexRoute;
  DashboardprimaryInboxIndexRoute: typeof DashboardprimaryInboxIndexRoute;
  DashboardSettingsNotificationsIndexRoute: typeof DashboardSettingsNotificationsIndexRoute;
  DashboardSettingsProfileIndexRoute: typeof DashboardSettingsProfileIndexRoute;
  DashboardSettingsSecurityIndexRoute: typeof DashboardSettingsSecurityIndexRoute;
  DashboardcoreAccountsNewIndexRoute: typeof DashboardcoreAccountsNewIndexRoute;
  DashboardcoreSessionKeysCreateIndexRoute: typeof DashboardcoreSessionKeysCreateIndexRoute;
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardprimaryIndexRoute: DashboardprimaryIndexRoute,
  DashboardSettingsIndexRoute: DashboardSettingsIndexRoute,
  DashboardagentsIdentityIndexRoute: DashboardagentsIdentityIndexRoute,
  DashboardagentsMcpIndexRoute: DashboardagentsMcpIndexRoute,
  DashboardcoreAccountsIndexRoute: DashboardcoreAccountsIndexRoute,
  DashboardcoreActivityIndexRoute: DashboardcoreActivityIndexRoute,
  DashboardcoreSessionKeysIndexRoute: DashboardcoreSessionKeysIndexRoute,
  DashboardcoreTemplatesIndexRoute: DashboardcoreTemplatesIndexRoute,
  DashboardprimaryAssetsIndexRoute: DashboardprimaryAssetsIndexRoute,
  DashboardprimaryInboxIndexRoute: DashboardprimaryInboxIndexRoute,
  DashboardSettingsNotificationsIndexRoute:
    DashboardSettingsNotificationsIndexRoute,
  DashboardSettingsProfileIndexRoute: DashboardSettingsProfileIndexRoute,
  DashboardSettingsSecurityIndexRoute: DashboardSettingsSecurityIndexRoute,
  DashboardcoreAccountsNewIndexRoute: DashboardcoreAccountsNewIndexRoute,
  DashboardcoreSessionKeysCreateIndexRoute:
    DashboardcoreSessionKeysCreateIndexRoute,
};

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  AuthIndexRoute: AuthIndexRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
