/** biome-ignore-all lint/style/useNamingConvention: safe */

/** biome-ignore-all lint/suspicious/noExplicitAny: safe  */

// @ts-nocheck

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./app/__root";
import { Route as AuthIndexRouteImport } from "./app/auth/index";
import { Route as DashboardAccountsIndexRouteImport } from "./app/dashboard/accounts/index";
import { Route as DashboardAccountsNewIndexRouteImport } from "./app/dashboard/accounts/new/index";
import { Route as DashboardActivityIndexRouteImport } from "./app/dashboard/activity/index";
import { Route as DashboardAssetsIndexRouteImport } from "./app/dashboard/assets/index";
import { Route as DashboardIdentityIndexRouteImport } from "./app/dashboard/identity/index";
import { Route as DashboardIndexRouteImport } from "./app/dashboard/index";
import { Route as DashboardMcpIndexRouteImport } from "./app/dashboard/mcp/index";
import { Route as DashboardPermissionsIndexRouteImport } from "./app/dashboard/permissions/index";
import { Route as DashboardRouteRouteImport } from "./app/dashboard/route";
import { Route as DashboardSessionKeysIndexRouteImport } from "./app/dashboard/session-keys/index";
import { Route as DashboardSettingsIndexRouteImport } from "./app/dashboard/settings/index";
import { Route as IndexRouteImport } from "./app/index";

const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: "/dashboard",
  path: "/dashboard",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => DashboardRouteRoute,
} as any);
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: "/auth/",
  path: "/auth/",
  getParentRoute: () => rootRouteImport,
} as any);
const DashboardSettingsIndexRoute = DashboardSettingsIndexRouteImport.update({
  id: "/settings/",
  path: "/settings/",
  getParentRoute: () => DashboardRouteRoute,
} as any);
const DashboardSessionKeysIndexRoute =
  DashboardSessionKeysIndexRouteImport.update({
    id: "/session-keys/",
    path: "/session-keys/",
    getParentRoute: () => DashboardRouteRoute,
  } as any);
const DashboardPermissionsIndexRoute =
  DashboardPermissionsIndexRouteImport.update({
    id: "/permissions/",
    path: "/permissions/",
    getParentRoute: () => DashboardRouteRoute,
  } as any);
const DashboardMcpIndexRoute = DashboardMcpIndexRouteImport.update({
  id: "/mcp/",
  path: "/mcp/",
  getParentRoute: () => DashboardRouteRoute,
} as any);
const DashboardIdentityIndexRoute = DashboardIdentityIndexRouteImport.update({
  id: "/identity/",
  path: "/identity/",
  getParentRoute: () => DashboardRouteRoute,
} as any);
const DashboardAssetsIndexRoute = DashboardAssetsIndexRouteImport.update({
  id: "/assets/",
  path: "/assets/",
  getParentRoute: () => DashboardRouteRoute,
} as any);
const DashboardActivityIndexRoute = DashboardActivityIndexRouteImport.update({
  id: "/activity/",
  path: "/activity/",
  getParentRoute: () => DashboardRouteRoute,
} as any);
const DashboardAccountsIndexRoute = DashboardAccountsIndexRouteImport.update({
  id: "/accounts/",
  path: "/accounts/",
  getParentRoute: () => DashboardRouteRoute,
} as any);
const DashboardAccountsNewIndexRoute =
  DashboardAccountsNewIndexRouteImport.update({
    id: "/accounts/new/",
    path: "/accounts/new/",
    getParentRoute: () => DashboardRouteRoute,
  } as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/dashboard": typeof DashboardRouteRouteWithChildren;
  "/auth/": typeof AuthIndexRoute;
  "/dashboard/": typeof DashboardIndexRoute;
  "/dashboard/accounts/": typeof DashboardAccountsIndexRoute;
  "/dashboard/activity/": typeof DashboardActivityIndexRoute;
  "/dashboard/assets/": typeof DashboardAssetsIndexRoute;
  "/dashboard/identity/": typeof DashboardIdentityIndexRoute;
  "/dashboard/mcp/": typeof DashboardMcpIndexRoute;
  "/dashboard/permissions/": typeof DashboardPermissionsIndexRoute;
  "/dashboard/session-keys/": typeof DashboardSessionKeysIndexRoute;
  "/dashboard/settings/": typeof DashboardSettingsIndexRoute;
  "/dashboard/accounts/new/": typeof DashboardAccountsNewIndexRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/auth": typeof AuthIndexRoute;
  "/dashboard": typeof DashboardIndexRoute;
  "/dashboard/accounts": typeof DashboardAccountsIndexRoute;
  "/dashboard/activity": typeof DashboardActivityIndexRoute;
  "/dashboard/assets": typeof DashboardAssetsIndexRoute;
  "/dashboard/identity": typeof DashboardIdentityIndexRoute;
  "/dashboard/mcp": typeof DashboardMcpIndexRoute;
  "/dashboard/permissions": typeof DashboardPermissionsIndexRoute;
  "/dashboard/session-keys": typeof DashboardSessionKeysIndexRoute;
  "/dashboard/settings": typeof DashboardSettingsIndexRoute;
  "/dashboard/accounts/new": typeof DashboardAccountsNewIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/dashboard": typeof DashboardRouteRouteWithChildren;
  "/auth/": typeof AuthIndexRoute;
  "/dashboard/": typeof DashboardIndexRoute;
  "/dashboard/accounts/": typeof DashboardAccountsIndexRoute;
  "/dashboard/activity/": typeof DashboardActivityIndexRoute;
  "/dashboard/assets/": typeof DashboardAssetsIndexRoute;
  "/dashboard/identity/": typeof DashboardIdentityIndexRoute;
  "/dashboard/mcp/": typeof DashboardMcpIndexRoute;
  "/dashboard/permissions/": typeof DashboardPermissionsIndexRoute;
  "/dashboard/session-keys/": typeof DashboardSessionKeysIndexRoute;
  "/dashboard/settings/": typeof DashboardSettingsIndexRoute;
  "/dashboard/accounts/new/": typeof DashboardAccountsNewIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/dashboard"
    | "/auth/"
    | "/dashboard/"
    | "/dashboard/accounts/"
    | "/dashboard/activity/"
    | "/dashboard/assets/"
    | "/dashboard/identity/"
    | "/dashboard/mcp/"
    | "/dashboard/permissions/"
    | "/dashboard/session-keys/"
    | "/dashboard/settings/"
    | "/dashboard/accounts/new/";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/auth"
    | "/dashboard"
    | "/dashboard/accounts"
    | "/dashboard/activity"
    | "/dashboard/assets"
    | "/dashboard/identity"
    | "/dashboard/mcp"
    | "/dashboard/permissions"
    | "/dashboard/session-keys"
    | "/dashboard/settings"
    | "/dashboard/accounts/new";
  id:
    | "__root__"
    | "/"
    | "/dashboard"
    | "/auth/"
    | "/dashboard/"
    | "/dashboard/accounts/"
    | "/dashboard/activity/"
    | "/dashboard/assets/"
    | "/dashboard/identity/"
    | "/dashboard/mcp/"
    | "/dashboard/permissions/"
    | "/dashboard/session-keys/"
    | "/dashboard/settings/"
    | "/dashboard/accounts/new/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren;
  AuthIndexRoute: typeof AuthIndexRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/dashboard": {
      id: "/dashboard";
      path: "/dashboard";
      fullPath: "/dashboard";
      preLoaderRoute: typeof DashboardRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/dashboard/": {
      id: "/dashboard/";
      path: "/";
      fullPath: "/dashboard/";
      preLoaderRoute: typeof DashboardIndexRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    "/auth/": {
      id: "/auth/";
      path: "/auth";
      fullPath: "/auth/";
      preLoaderRoute: typeof AuthIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/dashboard/settings/": {
      id: "/dashboard/settings/";
      path: "/settings";
      fullPath: "/dashboard/settings/";
      preLoaderRoute: typeof DashboardSettingsIndexRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    "/dashboard/session-keys/": {
      id: "/dashboard/session-keys/";
      path: "/session-keys";
      fullPath: "/dashboard/session-keys/";
      preLoaderRoute: typeof DashboardSessionKeysIndexRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    "/dashboard/permissions/": {
      id: "/dashboard/permissions/";
      path: "/permissions";
      fullPath: "/dashboard/permissions/";
      preLoaderRoute: typeof DashboardPermissionsIndexRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    "/dashboard/mcp/": {
      id: "/dashboard/mcp/";
      path: "/mcp";
      fullPath: "/dashboard/mcp/";
      preLoaderRoute: typeof DashboardMcpIndexRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    "/dashboard/identity/": {
      id: "/dashboard/identity/";
      path: "/identity";
      fullPath: "/dashboard/identity/";
      preLoaderRoute: typeof DashboardIdentityIndexRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    "/dashboard/assets/": {
      id: "/dashboard/assets/";
      path: "/assets";
      fullPath: "/dashboard/assets/";
      preLoaderRoute: typeof DashboardAssetsIndexRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    "/dashboard/activity/": {
      id: "/dashboard/activity/";
      path: "/activity";
      fullPath: "/dashboard/activity/";
      preLoaderRoute: typeof DashboardActivityIndexRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    "/dashboard/accounts/": {
      id: "/dashboard/accounts/";
      path: "/accounts";
      fullPath: "/dashboard/accounts/";
      preLoaderRoute: typeof DashboardAccountsIndexRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    "/dashboard/accounts/new/": {
      id: "/dashboard/accounts/new/";
      path: "/accounts/new";
      fullPath: "/dashboard/accounts/new/";
      preLoaderRoute: typeof DashboardAccountsNewIndexRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
  }
}

interface DashboardRouteRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute;
  DashboardAccountsIndexRoute: typeof DashboardAccountsIndexRoute;
  DashboardActivityIndexRoute: typeof DashboardActivityIndexRoute;
  DashboardAssetsIndexRoute: typeof DashboardAssetsIndexRoute;
  DashboardIdentityIndexRoute: typeof DashboardIdentityIndexRoute;
  DashboardMcpIndexRoute: typeof DashboardMcpIndexRoute;
  DashboardPermissionsIndexRoute: typeof DashboardPermissionsIndexRoute;
  DashboardSessionKeysIndexRoute: typeof DashboardSessionKeysIndexRoute;
  DashboardSettingsIndexRoute: typeof DashboardSettingsIndexRoute;
  DashboardAccountsNewIndexRoute: typeof DashboardAccountsNewIndexRoute;
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardAccountsIndexRoute: DashboardAccountsIndexRoute,
  DashboardActivityIndexRoute: DashboardActivityIndexRoute,
  DashboardAssetsIndexRoute: DashboardAssetsIndexRoute,
  DashboardIdentityIndexRoute: DashboardIdentityIndexRoute,
  DashboardMcpIndexRoute: DashboardMcpIndexRoute,
  DashboardPermissionsIndexRoute: DashboardPermissionsIndexRoute,
  DashboardSessionKeysIndexRoute: DashboardSessionKeysIndexRoute,
  DashboardSettingsIndexRoute: DashboardSettingsIndexRoute,
  DashboardAccountsNewIndexRoute: DashboardAccountsNewIndexRoute,
};

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  AuthIndexRoute: AuthIndexRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
