/** biome-ignore-all lint/style/useNamingConvention: safe */

/** biome-ignore-all lint/suspicious/noExplicitAny: safe  */

// @ts-nocheck

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./app/__root";
import { Route as DashboardRouteRouteImport } from "./app/dashboard/route";
import { Route as IndexRouteImport } from "./app/index";
import { Route as DashboardIndexRouteImport } from "./app/dashboard/index";
import { Route as AuthIndexRouteImport } from "./app/auth/index";
import { Route as DashboardSettingsIndexRouteImport } from "./app/dashboard/settings/index";
import { Route as DashboardAssetsIndexRouteImport } from "./app/dashboard/assets/index";
import { Route as DashboardcoreSessionKeysIndexRouteImport } from "./app/dashboard/(core)/session-keys/index";
import { Route as DashboardcorePermissionsIndexRouteImport } from "./app/dashboard/(core)/permissions/index";
import { Route as DashboardcoreActivityIndexRouteImport } from "./app/dashboard/(core)/activity/index";
import { Route as DashboardcoreAccountsIndexRouteImport } from "./app/dashboard/(core)/accounts/index";
import { Route as DashboardagentsMcpIndexRouteImport } from "./app/dashboard/(agents)/mcp/index";
import { Route as DashboardagentsIdentityIndexRouteImport } from "./app/dashboard/(agents)/identity/index";
import { Route as DashboardcoreAccountsNewIndexRouteImport } from "./app/dashboard/(core)/accounts/new/index";

const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: "/dashboard",
  path: "/dashboard",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => DashboardRouteRoute,
} as any);
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: "/auth/",
  path: "/auth/",
  getParentRoute: () => rootRouteImport,
} as any);
const DashboardSettingsIndexRoute = DashboardSettingsIndexRouteImport.update({
  id: "/settings/",
  path: "/settings/",
  getParentRoute: () => DashboardRouteRoute,
} as any);
const DashboardAssetsIndexRoute = DashboardAssetsIndexRouteImport.update({
  id: "/assets/",
  path: "/assets/",
  getParentRoute: () => DashboardRouteRoute,
} as any);
const DashboardcoreSessionKeysIndexRoute =
  DashboardcoreSessionKeysIndexRouteImport.update({
    id: "/(core)/session-keys/",
    path: "/session-keys/",
    getParentRoute: () => DashboardRouteRoute,
  } as any);
const DashboardcorePermissionsIndexRoute =
  DashboardcorePermissionsIndexRouteImport.update({
    id: "/(core)/permissions/",
    path: "/permissions/",
    getParentRoute: () => DashboardRouteRoute,
  } as any);
const DashboardcoreActivityIndexRoute =
  DashboardcoreActivityIndexRouteImport.update({
    id: "/(core)/activity/",
    path: "/activity/",
    getParentRoute: () => DashboardRouteRoute,
  } as any);
const DashboardcoreAccountsIndexRoute =
  DashboardcoreAccountsIndexRouteImport.update({
    id: "/(core)/accounts/",
    path: "/accounts/",
    getParentRoute: () => DashboardRouteRoute,
  } as any);
const DashboardagentsMcpIndexRoute = DashboardagentsMcpIndexRouteImport.update({
  id: "/(agents)/mcp/",
  path: "/mcp/",
  getParentRoute: () => DashboardRouteRoute,
} as any);
const DashboardagentsIdentityIndexRoute =
  DashboardagentsIdentityIndexRouteImport.update({
    id: "/(agents)/identity/",
    path: "/identity/",
    getParentRoute: () => DashboardRouteRoute,
  } as any);
const DashboardcoreAccountsNewIndexRoute =
  DashboardcoreAccountsNewIndexRouteImport.update({
    id: "/(core)/accounts/new/",
    path: "/accounts/new/",
    getParentRoute: () => DashboardRouteRoute,
  } as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/dashboard": typeof DashboardRouteRouteWithChildren;
  "/auth/": typeof AuthIndexRoute;
  "/dashboard/": typeof DashboardIndexRoute;
  "/dashboard/assets/": typeof DashboardAssetsIndexRoute;
  "/dashboard/settings/": typeof DashboardSettingsIndexRoute;
  "/dashboard/identity/": typeof DashboardagentsIdentityIndexRoute;
  "/dashboard/mcp/": typeof DashboardagentsMcpIndexRoute;
  "/dashboard/accounts/": typeof DashboardcoreAccountsIndexRoute;
  "/dashboard/activity/": typeof DashboardcoreActivityIndexRoute;
  "/dashboard/permissions/": typeof DashboardcorePermissionsIndexRoute;
  "/dashboard/session-keys/": typeof DashboardcoreSessionKeysIndexRoute;
  "/dashboard/accounts/new/": typeof DashboardcoreAccountsNewIndexRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/auth": typeof AuthIndexRoute;
  "/dashboard": typeof DashboardIndexRoute;
  "/dashboard/assets": typeof DashboardAssetsIndexRoute;
  "/dashboard/settings": typeof DashboardSettingsIndexRoute;
  "/dashboard/identity": typeof DashboardagentsIdentityIndexRoute;
  "/dashboard/mcp": typeof DashboardagentsMcpIndexRoute;
  "/dashboard/accounts": typeof DashboardcoreAccountsIndexRoute;
  "/dashboard/activity": typeof DashboardcoreActivityIndexRoute;
  "/dashboard/permissions": typeof DashboardcorePermissionsIndexRoute;
  "/dashboard/session-keys": typeof DashboardcoreSessionKeysIndexRoute;
  "/dashboard/accounts/new": typeof DashboardcoreAccountsNewIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/dashboard": typeof DashboardRouteRouteWithChildren;
  "/auth/": typeof AuthIndexRoute;
  "/dashboard/": typeof DashboardIndexRoute;
  "/dashboard/assets/": typeof DashboardAssetsIndexRoute;
  "/dashboard/settings/": typeof DashboardSettingsIndexRoute;
  "/dashboard/(agents)/identity/": typeof DashboardagentsIdentityIndexRoute;
  "/dashboard/(agents)/mcp/": typeof DashboardagentsMcpIndexRoute;
  "/dashboard/(core)/accounts/": typeof DashboardcoreAccountsIndexRoute;
  "/dashboard/(core)/activity/": typeof DashboardcoreActivityIndexRoute;
  "/dashboard/(core)/permissions/": typeof DashboardcorePermissionsIndexRoute;
  "/dashboard/(core)/session-keys/": typeof DashboardcoreSessionKeysIndexRoute;
  "/dashboard/(core)/accounts/new/": typeof DashboardcoreAccountsNewIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/dashboard"
    | "/auth/"
    | "/dashboard/"
    | "/dashboard/assets/"
    | "/dashboard/settings/"
    | "/dashboard/identity/"
    | "/dashboard/mcp/"
    | "/dashboard/accounts/"
    | "/dashboard/activity/"
    | "/dashboard/permissions/"
    | "/dashboard/session-keys/"
    | "/dashboard/accounts/new/";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/auth"
    | "/dashboard"
    | "/dashboard/assets"
    | "/dashboard/settings"
    | "/dashboard/identity"
    | "/dashboard/mcp"
    | "/dashboard/accounts"
    | "/dashboard/activity"
    | "/dashboard/permissions"
    | "/dashboard/session-keys"
    | "/dashboard/accounts/new";
  id:
    | "__root__"
    | "/"
    | "/dashboard"
    | "/auth/"
    | "/dashboard/"
    | "/dashboard/assets/"
    | "/dashboard/settings/"
    | "/dashboard/(agents)/identity/"
    | "/dashboard/(agents)/mcp/"
    | "/dashboard/(core)/accounts/"
    | "/dashboard/(core)/activity/"
    | "/dashboard/(core)/permissions/"
    | "/dashboard/(core)/session-keys/"
    | "/dashboard/(core)/accounts/new/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren;
  AuthIndexRoute: typeof AuthIndexRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/dashboard": {
      id: "/dashboard";
      path: "/dashboard";
      fullPath: "/dashboard";
      preLoaderRoute: typeof DashboardRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/dashboard/": {
      id: "/dashboard/";
      path: "/";
      fullPath: "/dashboard/";
      preLoaderRoute: typeof DashboardIndexRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    "/auth/": {
      id: "/auth/";
      path: "/auth";
      fullPath: "/auth/";
      preLoaderRoute: typeof AuthIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/dashboard/settings/": {
      id: "/dashboard/settings/";
      path: "/settings";
      fullPath: "/dashboard/settings/";
      preLoaderRoute: typeof DashboardSettingsIndexRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    "/dashboard/assets/": {
      id: "/dashboard/assets/";
      path: "/assets";
      fullPath: "/dashboard/assets/";
      preLoaderRoute: typeof DashboardAssetsIndexRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    "/dashboard/(core)/session-keys/": {
      id: "/dashboard/(core)/session-keys/";
      path: "/session-keys";
      fullPath: "/dashboard/session-keys/";
      preLoaderRoute: typeof DashboardcoreSessionKeysIndexRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    "/dashboard/(core)/permissions/": {
      id: "/dashboard/(core)/permissions/";
      path: "/permissions";
      fullPath: "/dashboard/permissions/";
      preLoaderRoute: typeof DashboardcorePermissionsIndexRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    "/dashboard/(core)/activity/": {
      id: "/dashboard/(core)/activity/";
      path: "/activity";
      fullPath: "/dashboard/activity/";
      preLoaderRoute: typeof DashboardcoreActivityIndexRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    "/dashboard/(core)/accounts/": {
      id: "/dashboard/(core)/accounts/";
      path: "/accounts";
      fullPath: "/dashboard/accounts/";
      preLoaderRoute: typeof DashboardcoreAccountsIndexRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    "/dashboard/(agents)/mcp/": {
      id: "/dashboard/(agents)/mcp/";
      path: "/mcp";
      fullPath: "/dashboard/mcp/";
      preLoaderRoute: typeof DashboardagentsMcpIndexRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    "/dashboard/(agents)/identity/": {
      id: "/dashboard/(agents)/identity/";
      path: "/identity";
      fullPath: "/dashboard/identity/";
      preLoaderRoute: typeof DashboardagentsIdentityIndexRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    "/dashboard/(core)/accounts/new/": {
      id: "/dashboard/(core)/accounts/new/";
      path: "/accounts/new";
      fullPath: "/dashboard/accounts/new/";
      preLoaderRoute: typeof DashboardcoreAccountsNewIndexRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
  }
}

interface DashboardRouteRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute;
  DashboardAssetsIndexRoute: typeof DashboardAssetsIndexRoute;
  DashboardSettingsIndexRoute: typeof DashboardSettingsIndexRoute;
  DashboardagentsIdentityIndexRoute: typeof DashboardagentsIdentityIndexRoute;
  DashboardagentsMcpIndexRoute: typeof DashboardagentsMcpIndexRoute;
  DashboardcoreAccountsIndexRoute: typeof DashboardcoreAccountsIndexRoute;
  DashboardcoreActivityIndexRoute: typeof DashboardcoreActivityIndexRoute;
  DashboardcorePermissionsIndexRoute: typeof DashboardcorePermissionsIndexRoute;
  DashboardcoreSessionKeysIndexRoute: typeof DashboardcoreSessionKeysIndexRoute;
  DashboardcoreAccountsNewIndexRoute: typeof DashboardcoreAccountsNewIndexRoute;
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardAssetsIndexRoute: DashboardAssetsIndexRoute,
  DashboardSettingsIndexRoute: DashboardSettingsIndexRoute,
  DashboardagentsIdentityIndexRoute: DashboardagentsIdentityIndexRoute,
  DashboardagentsMcpIndexRoute: DashboardagentsMcpIndexRoute,
  DashboardcoreAccountsIndexRoute: DashboardcoreAccountsIndexRoute,
  DashboardcoreActivityIndexRoute: DashboardcoreActivityIndexRoute,
  DashboardcorePermissionsIndexRoute: DashboardcorePermissionsIndexRoute,
  DashboardcoreSessionKeysIndexRoute: DashboardcoreSessionKeysIndexRoute,
  DashboardcoreAccountsNewIndexRoute: DashboardcoreAccountsNewIndexRoute,
};

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  AuthIndexRoute: AuthIndexRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
