/*
 * Every number on the pricing page comes from the billing architecture, not
 * from marketing:
 *
 *   architecture/billing/README.md   the Free v1 entitlement table, the
 *                                    anniversary period, and the rule that a
 *                                    meter either hard-caps or allows overage
 *   architecture/billing/pricing.md  the plan economics table generated by
 *                                    `pnpm billing:margin`
 *
 * Two things the architecture is explicit about, and this page honours:
 *
 *   - Only `free@1` is assignable today. `pro` and `business` are reserved
 *     keys with no paid-plan workflow behind them, so they are shown as what
 *     they are rather than as something anyone can buy.
 *   - The beta API rejects managed wallet creation and the dashboard does not
 *     advertise HSM entitlements, so neither does this page.
 *
 * Enterprise is not in the registry at all, not even as a reserved key. Its
 * column carries no figures for that reason: the price is "Custom", every cell
 * in the table is "Custom", and its lines are things to talk about rather than
 * things being claimed. The owner asked for the column; the numbers behind it
 * do not exist yet.
 */

export type PlanId = "free" | "pro" | "business" | "enterprise";

type Plan = {
  readonly id: PlanId;
  readonly name: string;
  readonly price: string;
  readonly cadence?: string;
  readonly summary: string;
  readonly available: boolean;
  /** What the column's action does. */
  readonly action: "waitlist" | "contact" | "none";
  /** What the column lists, in the order it reads. */
  readonly features: readonly string[];
};

export const PLANS: readonly Plan[] = [
  {
    id: "free",
    name: "Free",
    price: "$0",
    summary: "Free when it opens",
    available: true,
    action: "waitlist",
    features: [
      "5 members",
      "100 mainnet executions",
      "1,000 testnet executions",
      "10,000 signatures",
      "$3.00 of sponsored gas",
    ],
  },
  {
    id: "pro",
    name: "Pro",
    price: "$49",
    cadence: "per month",
    summary: "Not available yet",
    available: false,
    action: "none",
    features: [
      "Everything in Free, plus",
      "20 members",
      "2,000 mainnet executions",
      "50,000 signatures",
      "$5.00 of sponsored gas",
      "Keeps going past the limit, at cost",
    ],
  },
  {
    id: "business",
    name: "Business",
    price: "$249",
    cadence: "per month",
    summary: "Not available yet",
    available: false,
    action: "none",
    features: [
      "Everything in Pro, plus",
      "100 members",
      "10,000 mainnet executions",
      "250,000 signatures",
      "$15.00 of sponsored gas",
      "Keeps going past the limit, at cost",
    ],
  },
  {
    id: "enterprise",
    name: "Enterprise",
    price: "Custom",
    summary: "Tell us what you need",
    available: false,
    action: "contact",
    features: [
      "Everything in Business, plus",
      "Limits set to your volume",
      "Invoiced annually",
      "Support terms we agree with you",
    ],
  },
];

type Row = {
  readonly label: string;
  readonly note?: string;
  readonly values: Readonly<Record<PlanId, string>>;
};

type Group = {
  readonly title: string;
  readonly note?: string;
  readonly rows: readonly Row[];
};

export const GROUPS: readonly Group[] = [
  {
    title: "Your team",
    rows: [
      {
        label: "Members",
        note: "People in the organization. This one does not reset.",
        values: { free: "5", pro: "20", business: "100", enterprise: "Custom" },
      },
    ],
  },
  {
    title: "Each month",
    rows: [
      {
        label: "Mainnet executions",
        note: "One transaction sent and confirmed on a mainnet.",
        values: { free: "100", pro: "2,000", business: "10,000", enterprise: "Custom" },
      },
      {
        label: "Testnet executions",
        values: { free: "1,000", pro: "10,000", business: "50,000", enterprise: "Custom" },
      },
      {
        label: "Signatures",
        note: "Messages and typed data signed by a wallet.",
        values: { free: "10,000", pro: "50,000", business: "250,000", enterprise: "Custom" },
      },
      {
        label: "Sponsored gas",
        note: "Gas Namera pays on your behalf, counted at what it cost.",
        values: { free: "$3.00", pro: "$5.00", business: "$15.00", enterprise: "Custom" },
      },
    ],
  },
  {
    title: "Past the included amount",
    rows: [
      {
        label: "Extra executions",
        values: {
          free: "Stops at the limit",
          pro: "$3.00 per 1,000",
          business: "$3.00 per 1,000",
          enterprise: "Custom",
        },
      },
      {
        label: "Extra signatures",
        values: {
          free: "Stops at the limit",
          pro: "$1.00 per 10,000",
          business: "$1.00 per 10,000",
          enterprise: "Custom",
        },
      },
      {
        label: "Extra sponsored gas",
        values: {
          free: "Stops at the limit",
          pro: "Charged as used",
          business: "Charged as used",
          enterprise: "Custom",
        },
      },
    ],
  },
  {
    title: "On every plan",
    rows: [
      {
        label: "Chains",
        values: {
          free: "Ethereum, Base, Arbitrum, Optimism",
          pro: "Ethereum, Base, Arbitrum, Optimism",
          business: "Ethereum, Base, Arbitrum, Optimism",
          enterprise: "Ethereum, Base, Arbitrum, Optimism",
        },
      },
      {
        label: "Session keys",
        note: "Each one carries its own spend cap, network list and end date.",
        values: {
          free: "Unlimited",
          pro: "Unlimited",
          business: "Unlimited",
          enterprise: "Unlimited",
        },
      },
      {
        label: "Accounts owned by your passkey",
        values: { free: "Yes", pro: "Yes", business: "Yes", enterprise: "Yes" },
      },
      {
        label: "Signing keys stay on your machine",
        values: { free: "Yes", pro: "Yes", business: "Yes", enterprise: "Yes" },
      },
      {
        label: "Audit log on every wallet change",
        values: { free: "Yes", pro: "Yes", business: "Yes", enterprise: "Yes" },
      },
      {
        label: "MCP server, SDK and CLI",
        values: { free: "Yes", pro: "Yes", business: "Yes", enterprise: "Yes" },
      },
    ],
  },
];
