import type { CheckIcon } from "@thenamespace/uikit/icons";
import {
  AccessibilityIcon,
  Add01Icon,
  AiBrain01Icon,
  AirplayIcon,
  AlarmClockIcon,
  Album01Icon,
  Alert01Icon,
  Alert02Icon,
  AlertCircleIcon,
  AlertDiamondIcon,
  Analytics01Icon,
  AndroidIcon,
  Apple01Icon,
  AppleIcon,
  ArchiveIcon,
  ArrowDown01Icon,
  ArrowDownLeft01Icon,
  ArrowLeft01Icon,
  ArrowRight01Icon,
  ArrowUp01Icon,
  ArrowUpRight01Icon,
  AtIcon,
  BankIcon,
  BanknoteIcon,
  BasketballHoopIcon,
  BatteryFullIcon,
  BeachIcon,
  BitcoinIcon,
  BluetoothIcon,
  Book01Icon,
  Bookmark01Icon,
  Briefcase01Icon,
  BriefcaseDollarIcon,
  BubbleChatIcon,
  Bug01Icon,
  Building01Icon,
  Building02Icon,
  CalculatorIcon,
  Calendar01Icon,
  Calendar02Icon,
  Calendar03Icon,
  CalendarAdd01Icon,
  CalendarCheckIcon,
  CalendarClockIcon,
  CalendarDaysIcon,
  CalendarRangeIcon,
  CalendarSearchIcon,
  CalendarSetting01Icon,
  CallIcon,
  Camera01Icon,
  Camera02Icon,
  Cancel01Icon,
  CancelCircleIcon,
  Cash01Icon,
  Cash02Icon,
  ChampionIcon,
  ChartDownIcon,
  ChartUpIcon,
  Chatting01Icon,
  CheckmarkBadge01Icon,
  CheckmarkCircle01Icon,
  CheckmarkCircle02Icon,
  CherryIcon,
  ChevronDownIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ChevronUpIcon,
  ChromeIcon,
  ClapperboardIcon,
  ClipboardIcon,
  Clock01Icon,
  Clock02Icon,
  CloudIcon,
  CloudRainIcon,
  CloudSnowIcon,
  CodeIcon,
  CoffeeBeansIcon,
  Coins01Icon,
  CoinsDollarIcon,
  Compass01Icon,
  ComputerIcon,
  Contact01Icon,
  Copy01Icon,
  Coupon01Icon,
  CpuIcon,
  CreditCardIcon,
  CropIcon,
  CrownIcon,
  Csv01Icon,
  CubeIcon,
  CustomerServiceIcon,
  DashboardSquare01Icon,
  DatabaseIcon,
  Delete01Icon,
  DeliveryBox01Icon,
  DeliveryTruck01Icon,
  DiscountIcon,
  Doc01Icon,
  Doctor01Icon,
  DollarCircleIcon,
  DollarSquareIcon,
  Download01Icon,
  DragDropIcon,
  DropletIcon,
  EarthIcon,
  EcoEnergyIcon,
  Edit01Icon,
  EraserIcon,
  EthereumIcon,
  EyeIcon,
  FavouriteIcon,
  File01Icon,
  File02Icon,
  FileAddIcon,
  FileAttachmentIcon,
  FileDownloadIcon,
  FileEditIcon,
  FileExportIcon,
  FileImportIcon,
  FileSearchIcon,
  FileUploadIcon,
  FileValidationIcon,
  FileZipIcon,
  Film01Icon,
  FilterIcon,
  FireIcon,
  FireSecurityIcon,
  Flag01Icon,
  FlowerIcon,
  Folder01Icon,
  Folder02Icon,
  FolderAddIcon,
  FolderDownloadIcon,
  FolderEditIcon,
  FolderOpenIcon,
  FolderSearchIcon,
  FolderUploadIcon,
  GameController01Icon,
  GiftIcon,
  GlobalIcon,
  GlobeIcon,
  GridViewIcon,
  HandshakeIcon,
  HardDriveIcon,
  HeadphonesIcon,
  HeartIcon,
  HelpCircleIcon,
  HistoryIcon,
  Home01Icon,
  HourglassIcon,
  IdIcon,
  Idea01Icon,
  IdentityCardIcon,
  Image01Icon,
  Image02Icon,
  InboxIcon,
  Infinity01Icon,
  InformationCircleIcon,
  Invoice01Icon,
  Invoice02Icon,
  Key01Icon,
  KeyboardIcon,
  LaptopIcon,
  Layers01Icon,
  Layout01Icon,
  Leaf01Icon,
  Link01Icon,
  LockIcon,
  MagicWand01Icon,
  Mail01Icon,
  Mail02Icon,
  MailOpenIcon,
  MailReceive01Icon,
  MailSend01Icon,
  ManagerIcon,
  MapsIcon,
  MarketAnalysisIcon,
  Maximize01Icon,
  Megaphone01Icon,
  Menu01Icon,
  Message01Icon,
  Message02Icon,
  MessageAdd01Icon,
  MessageMultiple01Icon,
  Mic01Icon,
  Mic02Icon,
  Minimize01Icon,
  MinusSignIcon,
  Money01Icon,
  Money02Icon,
  Money03Icon,
  Moon01Icon,
  MoreHorizontalIcon,
  MoreVerticalIcon,
  MountainIcon,
  Mouse01Icon,
  MoveIcon,
  MusicNote01Icon,
  MusicNote02Icon,
  NextIcon,
  NoteIcon,
  NotebookIcon,
  Notification01Icon,
  Notification02Icon,
  Notification03Icon,
  NotificationOff01Icon,
  PackageIcon,
  PasswordValidationIcon,
  PauseIcon,
  Payment01Icon,
  Payment02Icon,
  Pdf01Icon,
  Pen01Icon,
  PencilEdit01Icon,
  PercentIcon,
  PiggyBankIcon,
  PinIcon,
  Plant01Icon,
  PlayIcon,
  Playlist01Icon,
  PodcastIcon,
  PoliceBadgeIcon,
  PreviousIcon,
  PrinterIcon,
  PuzzleIcon,
  QrCodeIcon,
  QuestionIcon,
  RadioIcon,
  RainbowIcon,
  ReceiptDollarIcon,
  RecordIcon,
  Recycle01Icon,
  RedoIcon,
  RefreshIcon,
  RepeatIcon,
  RepeatOne01Icon,
  Rocket01Icon,
  RouterIcon,
  RssIcon,
  RunningShoesIcon,
  SafariIcon,
  SafeIcon,
  SaleTag01Icon,
  ScanIcon,
  Search01Icon,
  SecurityIcon,
  SendToMobileIcon,
  ServerStack01Icon,
  Settings01Icon,
  ShapesIcon,
  Share01Icon,
  Shield01Icon,
  Shield02Icon,
  ShippingTruck01Icon,
  ShoppingBag01Icon,
  ShoppingBag02Icon,
  ShoppingCart01Icon,
  ShoppingCart02Icon,
  ShuffleIcon,
  SmartPhone01Icon,
  SmartWatch01Icon,
  SnowIcon,
  Sorting01Icon,
  SpamIcon,
  SparklesIcon,
  StarIcon,
  StopIcon,
  Store01Icon,
  Store02Icon,
  StoreVerified01Icon,
  StudentIcon,
  Sun01Icon,
  Tablet01Icon,
  Tag01Icon,
  Target01Icon,
  TeacherIcon,
  TelephoneIcon,
  TerminalIcon,
  TimeManagementIcon,
  TimeQuarterIcon,
  TimeScheduleIcon,
  Timer01Icon,
  Timer02Icon,
  Tree01Icon,
  UndoIcon,
  Unlink01Icon,
  Upload01Icon,
  UsbIcon,
  UserAccountIcon,
  UserAdd01Icon,
  UserCheck01Icon,
  UserCircleIcon,
  UserGroupIcon,
  UserIcon,
  UserMultipleIcon,
  UserRemove01Icon,
  UserSearch01Icon,
  UserSettings01Icon,
  UserSquareIcon,
  UserSwitchIcon,
  Video01Icon,
  Video02Icon,
  ViewOffIcon,
  VolumeHighIcon,
  VolumeLowIcon,
  VolumeMute01Icon,
  Wallet01Icon,
  Wallet02Icon,
  WaterEnergyIcon,
  WheatIcon,
  Wifi01Icon,
  WindPower01Icon,
  WindowsOldIcon,
  WorkoutRunIcon,
  Xls01Icon,
  YoutubeIcon,
  ZoomInAreaIcon,
  ZoomOutAreaIcon,
} from "@thenamespace/uikit/icons";

export type IconCategory =
  | "general"
  | "user"
  | "communication"
  | "files"
  | "time"
  | "finance"
  | "media"
  | "devices"
  | "actions"
  | "alerts"
  | "nature"
  | "commerce";

export type IconData = {
  icon: typeof CheckIcon;
  name: string;
  component: string;
  category: IconCategory;
  tags: string[];
};

// oxfmt-ignore
export const ICON_DATA: IconData[] = [
  // GENERAL (29)
  { name: "home-01", component: "Home 01", category: "general", tags: ["home"], icon: Home01Icon },
  { name: "dashboard-square-01", component: "Dashboard Square 01", category: "general", tags: ["dashboard","square"], icon: DashboardSquare01Icon },
  { name: "grid-view", component: "Grid View", category: "general", tags: ["grid","view"], icon: GridViewIcon },
  { name: "menu-01", component: "Menu 01", category: "general", tags: ["menu"], icon: Menu01Icon },
  { name: "compass-01", component: "Compass 01", category: "general", tags: ["compass"], icon: Compass01Icon },
  { name: "maps", component: "Maps", category: "general", tags: ["maps"], icon: MapsIcon },
  { name: "global", component: "Global", category: "general", tags: ["global"], icon: GlobalIcon },
  { name: "flag-01", component: "Flag 01", category: "general", tags: ["flag"], icon: Flag01Icon },
  { name: "bookmark-01", component: "Bookmark 01", category: "general", tags: ["bookmark"], icon: Bookmark01Icon },
  { name: "tag-01", component: "Tag 01", category: "general", tags: ["tag"], icon: Tag01Icon },
  { name: "pin", component: "Pin", category: "general", tags: ["pin"], icon: PinIcon },
  { name: "layout-01", component: "Layout 01", category: "general", tags: ["layout"], icon: Layout01Icon },
  { name: "layers-01", component: "Layers 01", category: "general", tags: ["layers"], icon: Layers01Icon },
  { name: "cube", component: "Cube", category: "general", tags: ["cube"], icon: CubeIcon },
  { name: "puzzle", component: "Puzzle", category: "general", tags: ["puzzle"], icon: PuzzleIcon },
  { name: "target-01", component: "Target 01", category: "general", tags: ["target"], icon: Target01Icon },
  { name: "rocket-01", component: "Rocket 01", category: "general", tags: ["rocket"], icon: Rocket01Icon },
  { name: "idea-01", component: "Idea 01", category: "general", tags: ["idea"], icon: Idea01Icon },
  { name: "ai-brain-01", component: "Ai Brain 01", category: "general", tags: ["ai","brain"], icon: AiBrain01Icon },
  { name: "magic-wand-01", component: "Magic Wand 01", category: "general", tags: ["magic","wand"], icon: MagicWand01Icon },
  { name: "sparkles", component: "Sparkles", category: "general", tags: ["sparkles"], icon: SparklesIcon },
  { name: "infinity-01", component: "Infinity 01", category: "general", tags: ["infinity"], icon: Infinity01Icon },
  { name: "shapes", component: "Shapes", category: "general", tags: ["shapes"], icon: ShapesIcon },
  { name: "pen-01", component: "Pen 01", category: "general", tags: ["pen"], icon: Pen01Icon },
  { name: "pencil-edit-01", component: "Pencil Edit 01", category: "general", tags: ["pencil","edit"], icon: PencilEdit01Icon },
  { name: "eraser", component: "Eraser", category: "general", tags: ["eraser"], icon: EraserIcon },
  { name: "key-01", component: "Key 01", category: "general", tags: ["key"], icon: Key01Icon },
  { name: "crown", component: "Crown", category: "general", tags: ["crown"], icon: CrownIcon },
  { name: "building-01", component: "Building 01", category: "general", tags: ["building"], icon: Building01Icon },

  // USER (25)
  { name: "user", component: "User", category: "user", tags: ["user"], icon: UserIcon },
  { name: "user-circle", component: "User Circle", category: "user", tags: ["user","circle"], icon: UserCircleIcon },
  { name: "user-square", component: "User Square", category: "user", tags: ["user","square"], icon: UserSquareIcon },
  { name: "user-group", component: "User Group", category: "user", tags: ["user","group"], icon: UserGroupIcon },
  { name: "user-multiple", component: "User Multiple", category: "user", tags: ["user","multiple"], icon: UserMultipleIcon },
  { name: "user-add-01", component: "User Add 01", category: "user", tags: ["user","add"], icon: UserAdd01Icon },
  { name: "user-remove-01", component: "User Remove 01", category: "user", tags: ["user","remove"], icon: UserRemove01Icon },
  { name: "user-check-01", component: "User Check 01", category: "user", tags: ["user","check"], icon: UserCheck01Icon },
  { name: "user-settings-01", component: "User Settings 01", category: "user", tags: ["user","settings"], icon: UserSettings01Icon },
  { name: "user-switch", component: "User Switch", category: "user", tags: ["user","switch"], icon: UserSwitchIcon },
  { name: "user-search-01", component: "User Search 01", category: "user", tags: ["user","search"], icon: UserSearch01Icon },
  { name: "user-account", component: "User Account", category: "user", tags: ["user","account"], icon: UserAccountIcon },
  { name: "contact-01", component: "Contact 01", category: "user", tags: ["contact"], icon: Contact01Icon },
  { name: "identity-card", component: "Identity Card", category: "user", tags: ["identity","card"], icon: IdentityCardIcon },
  { name: "id", component: "Id", category: "user", tags: ["id"], icon: IdIcon },
  { name: "handshake", component: "Handshake", category: "user", tags: ["handshake"], icon: HandshakeIcon },
  { name: "favourite", component: "Favourite", category: "user", tags: ["favourite"], icon: FavouriteIcon },
  { name: "champion", component: "Champion", category: "user", tags: ["champion"], icon: ChampionIcon },
  { name: "manager", component: "Manager", category: "user", tags: ["manager"], icon: ManagerIcon },
  { name: "teacher", component: "Teacher", category: "user", tags: ["teacher"], icon: TeacherIcon },
  { name: "student", component: "Student", category: "user", tags: ["student"], icon: StudentIcon },
  { name: "doctor-01", component: "Doctor 01", category: "user", tags: ["doctor"], icon: Doctor01Icon },
  { name: "running-shoes", component: "Running Shoes", category: "user", tags: ["running","shoes"], icon: RunningShoesIcon },
  { name: "workout-run", component: "Workout Run", category: "user", tags: ["workout","run"], icon: WorkoutRunIcon },
  { name: "accessibility", component: "Accessibility", category: "user", tags: ["accessibility"], icon: AccessibilityIcon },

  // COMMUNICATION (25)
  { name: "mail-01", component: "Mail 01", category: "communication", tags: ["mail"], icon: Mail01Icon },
  { name: "mail-02", component: "Mail 02", category: "communication", tags: ["mail"], icon: Mail02Icon },
  { name: "mail-open", component: "Mail Open", category: "communication", tags: ["mail","open"], icon: MailOpenIcon },
  { name: "mail-send-01", component: "Mail Send 01", category: "communication", tags: ["mail","send"], icon: MailSend01Icon },
  { name: "mail-receive-01", component: "Mail Receive 01", category: "communication", tags: ["mail","receive"], icon: MailReceive01Icon },
  { name: "message-01", component: "Message 01", category: "communication", tags: ["message"], icon: Message01Icon },
  { name: "message-02", component: "Message 02", category: "communication", tags: ["message"], icon: Message02Icon },
  { name: "message-add-01", component: "Message Add 01", category: "communication", tags: ["message","add"], icon: MessageAdd01Icon },
  { name: "message-multiple-01", component: "Message Multiple 01", category: "communication", tags: ["message","multiple"], icon: MessageMultiple01Icon },
  { name: "chatting-01", component: "Chatting 01", category: "communication", tags: ["chatting"], icon: Chatting01Icon },
  { name: "bubble-chat", component: "Bubble Chat", category: "communication", tags: ["bubble","chat"], icon: BubbleChatIcon },
  { name: "call", component: "Call", category: "communication", tags: ["call"], icon: CallIcon },
  { name: "telephone", component: "Telephone", category: "communication", tags: ["telephone"], icon: TelephoneIcon },
  { name: "video-01", component: "Video 01", category: "communication", tags: ["video"], icon: Video01Icon },
  { name: "mic-01", component: "Mic 01", category: "communication", tags: ["mic"], icon: Mic01Icon },
  { name: "notification-01", component: "Notification 01", category: "communication", tags: ["notification"], icon: Notification01Icon },
  { name: "notification-02", component: "Notification 02", category: "communication", tags: ["notification"], icon: Notification02Icon },
  { name: "megaphone-01", component: "Megaphone 01", category: "communication", tags: ["megaphone"], icon: Megaphone01Icon },
  { name: "share-01", component: "Share 01", category: "communication", tags: ["share"], icon: Share01Icon },
  { name: "link-01", component: "Link 01", category: "communication", tags: ["link"], icon: Link01Icon },
  { name: "at", component: "At", category: "communication", tags: ["at"], icon: AtIcon },
  { name: "inbox", component: "Inbox", category: "communication", tags: ["inbox"], icon: InboxIcon },
  { name: "send-to-mobile", component: "Send To Mobile", category: "communication", tags: ["send","to","mobile"], icon: SendToMobileIcon },
  { name: "wifi-01", component: "Wifi 01", category: "communication", tags: ["wifi"], icon: Wifi01Icon },
  { name: "rss", component: "Rss", category: "communication", tags: ["rss"], icon: RssIcon },

  // FILES (29)
  { name: "file-01", component: "File 01", category: "files", tags: ["file"], icon: File01Icon },
  { name: "file-02", component: "File 02", category: "files", tags: ["file"], icon: File02Icon },
  { name: "file-add", component: "File Add", category: "files", tags: ["file","add"], icon: FileAddIcon },
  { name: "file-edit", component: "File Edit", category: "files", tags: ["file","edit"], icon: FileEditIcon },
  { name: "file-search", component: "File Search", category: "files", tags: ["file","search"], icon: FileSearchIcon },
  { name: "file-download", component: "File Download", category: "files", tags: ["file","download"], icon: FileDownloadIcon },
  { name: "file-upload", component: "File Upload", category: "files", tags: ["file","upload"], icon: FileUploadIcon },
  { name: "file-attachment", component: "File Attachment", category: "files", tags: ["file","attachment"], icon: FileAttachmentIcon },
  { name: "file-import", component: "File Import", category: "files", tags: ["file","import"], icon: FileImportIcon },
  { name: "file-export", component: "File Export", category: "files", tags: ["file","export"], icon: FileExportIcon },
  { name: "file-validation", component: "File Validation", category: "files", tags: ["file","validation"], icon: FileValidationIcon },
  { name: "file-zip", component: "File Zip", category: "files", tags: ["file","zip"], icon: FileZipIcon },
  { name: "pdf-01", component: "Pdf 01", category: "files", tags: ["pdf"], icon: Pdf01Icon },
  { name: "doc-01", component: "Doc 01", category: "files", tags: ["doc"], icon: Doc01Icon },
  { name: "xls-01", component: "Xls 01", category: "files", tags: ["xls"], icon: Xls01Icon },
  { name: "csv-01", component: "Csv 01", category: "files", tags: ["csv"], icon: Csv01Icon },
  { name: "folder-01", component: "Folder 01", category: "files", tags: ["folder"], icon: Folder01Icon },
  { name: "folder-02", component: "Folder 02", category: "files", tags: ["folder"], icon: Folder02Icon },
  { name: "folder-add", component: "Folder Add", category: "files", tags: ["folder","add"], icon: FolderAddIcon },
  { name: "folder-open", component: "Folder Open", category: "files", tags: ["folder","open"], icon: FolderOpenIcon },
  { name: "folder-search", component: "Folder Search", category: "files", tags: ["folder","search"], icon: FolderSearchIcon },
  { name: "folder-download", component: "Folder Download", category: "files", tags: ["folder","download"], icon: FolderDownloadIcon },
  { name: "folder-upload", component: "Folder Upload", category: "files", tags: ["folder","upload"], icon: FolderUploadIcon },
  { name: "folder-edit", component: "Folder Edit", category: "files", tags: ["folder","edit"], icon: FolderEditIcon },
  { name: "clipboard", component: "Clipboard", category: "files", tags: ["clipboard"], icon: ClipboardIcon },
  { name: "note", component: "Note", category: "files", tags: ["note"], icon: NoteIcon },
  { name: "notebook", component: "Notebook", category: "files", tags: ["notebook"], icon: NotebookIcon },
  { name: "book-01", component: "Book 01", category: "files", tags: ["book"], icon: Book01Icon },
  { name: "archive", component: "Archive", category: "files", tags: ["archive"], icon: ArchiveIcon },

  // TIME (27)
  { name: "calendar-01", component: "Calendar 01", category: "time", tags: ["calendar"], icon: Calendar01Icon },
  { name: "calendar-02", component: "Calendar 02", category: "time", tags: ["calendar"], icon: Calendar02Icon },
  { name: "calendar-03", component: "Calendar 03", category: "time", tags: ["calendar"], icon: Calendar03Icon },
  { name: "calendar-add-01", component: "Calendar Add 01", category: "time", tags: ["calendar","add"], icon: CalendarAdd01Icon },
  { name: "calendar-check", component: "Calendar Check", category: "time", tags: ["calendar","check"], icon: CalendarCheckIcon },
  { name: "calendar-clock", component: "Calendar Clock", category: "time", tags: ["calendar","clock"], icon: CalendarClockIcon },
  { name: "calendar-days", component: "Calendar Days", category: "time", tags: ["calendar","days"], icon: CalendarDaysIcon },
  { name: "calendar-range", component: "Calendar Range", category: "time", tags: ["calendar","range"], icon: CalendarRangeIcon },
  { name: "calendar-search", component: "Calendar Search", category: "time", tags: ["calendar","search"], icon: CalendarSearchIcon },
  { name: "calendar-setting-01", component: "Calendar Setting 01", category: "time", tags: ["calendar","setting"], icon: CalendarSetting01Icon },
  { name: "clock-01", component: "Clock 01", category: "time", tags: ["clock"], icon: Clock01Icon },
  { name: "clock-02", component: "Clock 02", category: "time", tags: ["clock"], icon: Clock02Icon },
  { name: "alarm-clock", component: "Alarm Clock", category: "time", tags: ["alarm","clock"], icon: AlarmClockIcon },
  { name: "timer-01", component: "Timer 01", category: "time", tags: ["timer"], icon: Timer01Icon },
  { name: "timer-02", component: "Timer 02", category: "time", tags: ["timer"], icon: Timer02Icon },
  { name: "hourglass", component: "Hourglass", category: "time", tags: ["hourglass"], icon: HourglassIcon },
  { name: "time-quarter", component: "Time Quarter", category: "time", tags: ["time","quarter"], icon: TimeQuarterIcon },
  { name: "time-management", component: "Time Management", category: "time", tags: ["time","management"], icon: TimeManagementIcon },
  { name: "time-schedule", component: "Time Schedule", category: "time", tags: ["time","schedule"], icon: TimeScheduleIcon },
  { name: "history", component: "History", category: "time", tags: ["history"], icon: HistoryIcon },
  { name: "refresh", component: "Refresh", category: "time", tags: ["refresh"], icon: RefreshIcon },
  { name: "repeat", component: "Repeat", category: "time", tags: ["repeat"], icon: RepeatIcon },
  { name: "repeat-one-01", component: "Repeat One 01", category: "time", tags: ["repeat","one"], icon: RepeatOne01Icon },
  { name: "undo", component: "Undo", category: "time", tags: ["undo"], icon: UndoIcon },
  { name: "redo", component: "Redo", category: "time", tags: ["redo"], icon: RedoIcon },
  { name: "play", component: "Play", category: "time", tags: ["play"], icon: PlayIcon },
  { name: "pause", component: "Pause", category: "time", tags: ["pause"], icon: PauseIcon },

  // FINANCE (29)
  { name: "wallet-01", component: "Wallet 01", category: "finance", tags: ["wallet"], icon: Wallet01Icon },
  { name: "wallet-02", component: "Wallet 02", category: "finance", tags: ["wallet"], icon: Wallet02Icon },
  { name: "money-01", component: "Money 01", category: "finance", tags: ["money"], icon: Money01Icon },
  { name: "money-02", component: "Money 02", category: "finance", tags: ["money"], icon: Money02Icon },
  { name: "money-03", component: "Money 03", category: "finance", tags: ["money"], icon: Money03Icon },
  { name: "dollar-circle", component: "Dollar Circle", category: "finance", tags: ["dollar","circle"], icon: DollarCircleIcon },
  { name: "dollar-square", component: "Dollar Square", category: "finance", tags: ["dollar","square"], icon: DollarSquareIcon },
  { name: "bank", component: "Bank", category: "finance", tags: ["bank"], icon: BankIcon },
  { name: "banknote", component: "Banknote", category: "finance", tags: ["banknote"], icon: BanknoteIcon },
  { name: "credit-card", component: "Credit Card", category: "finance", tags: ["credit","card"], icon: CreditCardIcon },
  { name: "invoice-01", component: "Invoice 01", category: "finance", tags: ["invoice"], icon: Invoice01Icon },
  { name: "invoice-02", component: "Invoice 02", category: "finance", tags: ["invoice"], icon: Invoice02Icon },
  { name: "receipt-dollar", component: "Receipt Dollar", category: "finance", tags: ["receipt","dollar"], icon: ReceiptDollarIcon },
  { name: "cash-01", component: "Cash 01", category: "finance", tags: ["cash"], icon: Cash01Icon },
  { name: "cash-02", component: "Cash 02", category: "finance", tags: ["cash"], icon: Cash02Icon },
  { name: "coins-01", component: "Coins 01", category: "finance", tags: ["coins"], icon: Coins01Icon },
  { name: "coins-dollar", component: "Coins Dollar", category: "finance", tags: ["coins","dollar"], icon: CoinsDollarIcon },
  { name: "payment-01", component: "Payment 01", category: "finance", tags: ["payment"], icon: Payment01Icon },
  { name: "payment-02", component: "Payment 02", category: "finance", tags: ["payment"], icon: Payment02Icon },
  { name: "piggy-bank", component: "Piggy Bank", category: "finance", tags: ["piggy","bank"], icon: PiggyBankIcon },
  { name: "safe", component: "Safe", category: "finance", tags: ["safe"], icon: SafeIcon },
  { name: "chart-up", component: "Chart Up", category: "finance", tags: ["chart","up"], icon: ChartUpIcon },
  { name: "chart-down", component: "Chart Down", category: "finance", tags: ["chart","down"], icon: ChartDownIcon },
  { name: "analytics-01", component: "Analytics 01", category: "finance", tags: ["analytics"], icon: Analytics01Icon },
  { name: "calculator", component: "Calculator", category: "finance", tags: ["calculator"], icon: CalculatorIcon },
  { name: "percent", component: "Percent", category: "finance", tags: ["percent"], icon: PercentIcon },
  { name: "bitcoin", component: "Bitcoin", category: "finance", tags: ["bitcoin"], icon: BitcoinIcon },
  { name: "ethereum", component: "Ethereum", category: "finance", tags: ["ethereum"], icon: EthereumIcon },
  { name: "briefcase-dollar", component: "Briefcase Dollar", category: "finance", tags: ["briefcase","dollar"], icon: BriefcaseDollarIcon },

  // MEDIA (28)
  { name: "play-media", component: "Play", category: "media", tags: ["play"], icon: PlayIcon },
  { name: "pause-media", component: "Pause", category: "media", tags: ["pause"], icon: PauseIcon },
  { name: "stop", component: "Stop", category: "media", tags: ["stop"], icon: StopIcon },
  { name: "record", component: "Record", category: "media", tags: ["record"], icon: RecordIcon },
  { name: "previous", component: "Previous", category: "media", tags: ["previous"], icon: PreviousIcon },
  { name: "next", component: "Next", category: "media", tags: ["next"], icon: NextIcon },
  { name: "music-note-01", component: "Music Note 01", category: "media", tags: ["music","note"], icon: MusicNote01Icon },
  { name: "music-note-02", component: "Music Note 02", category: "media", tags: ["music","note"], icon: MusicNote02Icon },
  { name: "playlist-01", component: "Playlist 01", category: "media", tags: ["playlist"], icon: Playlist01Icon },
  { name: "album-01", component: "Album 01", category: "media", tags: ["album"], icon: Album01Icon },
  { name: "camera-01", component: "Camera 01", category: "media", tags: ["camera"], icon: Camera01Icon },
  { name: "camera-02", component: "Camera 02", category: "media", tags: ["camera"], icon: Camera02Icon },
  { name: "video-01-media", component: "Video 01", category: "media", tags: ["video"], icon: Video01Icon },
  { name: "video-02", component: "Video 02", category: "media", tags: ["video"], icon: Video02Icon },
  { name: "mic-01-media", component: "Mic 01", category: "media", tags: ["mic"], icon: Mic01Icon },
  { name: "mic-02", component: "Mic 02", category: "media", tags: ["mic"], icon: Mic02Icon },
  { name: "volume-high", component: "Volume High", category: "media", tags: ["volume","high"], icon: VolumeHighIcon },
  { name: "volume-low", component: "Volume Low", category: "media", tags: ["volume","low"], icon: VolumeLowIcon },
  { name: "volume-mute-01", component: "Volume Mute 01", category: "media", tags: ["volume","mute"], icon: VolumeMute01Icon },
  { name: "headphones", component: "Headphones", category: "media", tags: ["headphones"], icon: HeadphonesIcon },
  { name: "radio", component: "Radio", category: "media", tags: ["radio"], icon: RadioIcon },
  { name: "podcast", component: "Podcast", category: "media", tags: ["podcast"], icon: PodcastIcon },
  { name: "image-01", component: "Image 01", category: "media", tags: ["image"], icon: Image01Icon },
  { name: "image-02", component: "Image 02", category: "media", tags: ["image"], icon: Image02Icon },
  { name: "film-01", component: "Film 01", category: "media", tags: ["film"], icon: Film01Icon },
  { name: "clapperboard", component: "Clapperboard", category: "media", tags: ["clapperboard"], icon: ClapperboardIcon },
  { name: "youtube", component: "Youtube", category: "media", tags: ["youtube"], icon: YoutubeIcon },
  { name: "airplay", component: "Airplay", category: "media", tags: ["airplay"], icon: AirplayIcon },

  // DEVICES (26)
  { name: "laptop", component: "Laptop", category: "devices", tags: ["laptop"], icon: LaptopIcon },
  { name: "computer", component: "Computer", category: "devices", tags: ["computer"], icon: ComputerIcon },
  { name: "smart-phone-01", component: "Smart Phone 01", category: "devices", tags: ["smart","phone"], icon: SmartPhone01Icon },
  { name: "tablet-01", component: "Tablet 01", category: "devices", tags: ["tablet"], icon: Tablet01Icon },
  { name: "smart-watch-01", component: "Smart Watch 01", category: "devices", tags: ["smart","watch"], icon: SmartWatch01Icon },
  { name: "keyboard", component: "Keyboard", category: "devices", tags: ["keyboard"], icon: KeyboardIcon },
  { name: "mouse-01", component: "Mouse 01", category: "devices", tags: ["mouse"], icon: Mouse01Icon },
  { name: "printer", component: "Printer", category: "devices", tags: ["printer"], icon: PrinterIcon },
  { name: "cpu", component: "Cpu", category: "devices", tags: ["cpu"], icon: CpuIcon },
  { name: "database", component: "Database", category: "devices", tags: ["database"], icon: DatabaseIcon },
  { name: "server-stack-01", component: "Server Stack 01", category: "devices", tags: ["server","stack"], icon: ServerStack01Icon },
  { name: "cloud", component: "Cloud", category: "devices", tags: ["cloud"], icon: CloudIcon },
  { name: "wifi-01-devices", component: "Wifi 01", category: "devices", tags: ["wifi"], icon: Wifi01Icon },
  { name: "bluetooth", component: "Bluetooth", category: "devices", tags: ["bluetooth"], icon: BluetoothIcon },
  { name: "usb", component: "Usb", category: "devices", tags: ["usb"], icon: UsbIcon },
  { name: "hard-drive", component: "Hard Drive", category: "devices", tags: ["hard","drive"], icon: HardDriveIcon },
  { name: "battery-full", component: "Battery Full", category: "devices", tags: ["battery","full"], icon: BatteryFullIcon },
  { name: "router", component: "Router", category: "devices", tags: ["router"], icon: RouterIcon },
  { name: "game-controller-01", component: "Game Controller 01", category: "devices", tags: ["game","controller"], icon: GameController01Icon },
  { name: "apple", component: "Apple", category: "devices", tags: ["apple"], icon: AppleIcon },
  { name: "android", component: "Android", category: "devices", tags: ["android"], icon: AndroidIcon },
  { name: "chrome", component: "Chrome", category: "devices", tags: ["chrome"], icon: ChromeIcon },
  { name: "safari", component: "Safari", category: "devices", tags: ["safari"], icon: SafariIcon },
  { name: "windows-old", component: "Windows Old", category: "devices", tags: ["windows","old"], icon: WindowsOldIcon },
  { name: "code", component: "Code", category: "devices", tags: ["code"], icon: CodeIcon },
  { name: "terminal", component: "Terminal", category: "devices", tags: ["terminal"], icon: TerminalIcon },

  // ACTIONS (39)
  { name: "add-01", component: "Add 01", category: "actions", tags: ["add"], icon: Add01Icon },
  { name: "minus-sign", component: "Minus Sign", category: "actions", tags: ["minus","sign"], icon: MinusSignIcon },
  { name: "checkmark-circle-02", component: "Checkmark Circle 02", category: "actions", tags: ["checkmark","circle"], icon: CheckmarkCircle02Icon },
  { name: "cancel-01", component: "Cancel 01", category: "actions", tags: ["cancel"], icon: Cancel01Icon },
  { name: "cancel-circle", component: "Cancel Circle", category: "actions", tags: ["cancel","circle"], icon: CancelCircleIcon },
  { name: "copy-01", component: "Copy 01", category: "actions", tags: ["copy"], icon: Copy01Icon },
  { name: "download-01", component: "Download 01", category: "actions", tags: ["download"], icon: Download01Icon },
  { name: "upload-01", component: "Upload 01", category: "actions", tags: ["upload"], icon: Upload01Icon },
  { name: "share-01-actions", component: "Share 01", category: "actions", tags: ["share"], icon: Share01Icon },
  { name: "link-01-actions", component: "Link 01", category: "actions", tags: ["link"], icon: Link01Icon },
  { name: "unlink-01", component: "Unlink 01", category: "actions", tags: ["unlink"], icon: Unlink01Icon },
  { name: "search-01", component: "Search 01", category: "actions", tags: ["search"], icon: Search01Icon },
  { name: "filter", component: "Filter", category: "actions", tags: ["filter"], icon: FilterIcon },
  { name: "sorting-01", component: "Sorting 01", category: "actions", tags: ["sorting"], icon: Sorting01Icon },
  { name: "refresh-actions", component: "Refresh", category: "actions", tags: ["refresh"], icon: RefreshIcon },
  { name: "repeat-actions", component: "Repeat", category: "actions", tags: ["repeat"], icon: RepeatIcon },
  { name: "shuffle", component: "Shuffle", category: "actions", tags: ["shuffle"], icon: ShuffleIcon },
  { name: "arrow-up-01", component: "Arrow Up 01", category: "actions", tags: ["arrow","up"], icon: ArrowUp01Icon },
  { name: "arrow-down-01", component: "Arrow Down 01", category: "actions", tags: ["arrow","down"], icon: ArrowDown01Icon },
  { name: "arrow-left-01", component: "Arrow Left 01", category: "actions", tags: ["arrow","left"], icon: ArrowLeft01Icon },
  { name: "arrow-right-01", component: "Arrow Right 01", category: "actions", tags: ["arrow","right"], icon: ArrowRight01Icon },
  { name: "arrow-up-right-01", component: "Arrow Up Right 01", category: "actions", tags: ["arrow","up","right"], icon: ArrowUpRight01Icon },
  { name: "arrow-down-left-01", component: "Arrow Down Left 01", category: "actions", tags: ["arrow","down","left"], icon: ArrowDownLeft01Icon },
  { name: "chevron-up", component: "Chevron Up", category: "actions", tags: ["chevron","up"], icon: ChevronUpIcon },
  { name: "chevron-down", component: "Chevron Down", category: "actions", tags: ["chevron","down"], icon: ChevronDownIcon },
  { name: "chevron-left", component: "Chevron Left", category: "actions", tags: ["chevron","left"], icon: ChevronLeftIcon },
  { name: "chevron-right", component: "Chevron Right", category: "actions", tags: ["chevron","right"], icon: ChevronRightIcon },
  { name: "more-horizontal", component: "More Horizontal", category: "actions", tags: ["more","horizontal"], icon: MoreHorizontalIcon },
  { name: "more-vertical", component: "More Vertical", category: "actions", tags: ["more","vertical"], icon: MoreVerticalIcon },
  { name: "edit-01", component: "Edit 01", category: "actions", tags: ["edit"], icon: Edit01Icon },
  { name: "delete-01", component: "Delete 01", category: "actions", tags: ["delete"], icon: Delete01Icon },
  { name: "settings-01", component: "Settings 01", category: "actions", tags: ["settings"], icon: Settings01Icon },
  { name: "zoom-in-area", component: "Zoom In Area", category: "actions", tags: ["zoom","in","area"], icon: ZoomInAreaIcon },
  { name: "zoom-out-area", component: "Zoom Out Area", category: "actions", tags: ["zoom","out","area"], icon: ZoomOutAreaIcon },
  { name: "crop", component: "Crop", category: "actions", tags: ["crop"], icon: CropIcon },
  { name: "move", component: "Move", category: "actions", tags: ["move"], icon: MoveIcon },
  { name: "drag-drop", component: "Drag Drop", category: "actions", tags: ["drag","drop"], icon: DragDropIcon },
  { name: "maximize-01", component: "Maximize 01", category: "actions", tags: ["maximize"], icon: Maximize01Icon },
  { name: "minimize-01", component: "Minimize 01", category: "actions", tags: ["minimize"], icon: Minimize01Icon },

  // ALERTS (28)
  { name: "alert-01", component: "Alert 01", category: "alerts", tags: ["alert"], icon: Alert01Icon },
  { name: "alert-02", component: "Alert 02", category: "alerts", tags: ["alert"], icon: Alert02Icon },
  { name: "alert-circle", component: "Alert Circle", category: "alerts", tags: ["alert","circle"], icon: AlertCircleIcon },
  { name: "alert-diamond", component: "Alert Diamond", category: "alerts", tags: ["alert","diamond"], icon: AlertDiamondIcon },
  { name: "information-circle", component: "Information Circle", category: "alerts", tags: ["information","circle"], icon: InformationCircleIcon },
  { name: "help-circle", component: "Help Circle", category: "alerts", tags: ["help","circle"], icon: HelpCircleIcon },
  { name: "question", component: "Question", category: "alerts", tags: ["question"], icon: QuestionIcon },
  { name: "security", component: "Security", category: "alerts", tags: ["security"], icon: SecurityIcon },
  { name: "shield-01", component: "Shield 01", category: "alerts", tags: ["shield"], icon: Shield01Icon },
  { name: "shield-02", component: "Shield 02", category: "alerts", tags: ["shield"], icon: Shield02Icon },
  { name: "lock", component: "Lock", category: "alerts", tags: ["lock"], icon: LockIcon },
  { name: "key-01-alerts", component: "Key 01", category: "alerts", tags: ["key"], icon: Key01Icon },
  { name: "notification-01-alerts", component: "Notification 01", category: "alerts", tags: ["notification"], icon: Notification01Icon },
  { name: "notification-02-alerts", component: "Notification 02", category: "alerts", tags: ["notification"], icon: Notification02Icon },
  { name: "notification-03", component: "Notification 03", category: "alerts", tags: ["notification"], icon: Notification03Icon },
  { name: "notification-off-01", component: "Notification Off 01", category: "alerts", tags: ["notification","off"], icon: NotificationOff01Icon },
  { name: "bug-01", component: "Bug 01", category: "alerts", tags: ["bug"], icon: Bug01Icon },
  { name: "fire-security", component: "Fire Security", category: "alerts", tags: ["fire","security"], icon: FireSecurityIcon },
  { name: "police-badge", component: "Police Badge", category: "alerts", tags: ["police","badge"], icon: PoliceBadgeIcon },
  { name: "eye", component: "Eye", category: "alerts", tags: ["eye"], icon: EyeIcon },
  { name: "view-off", component: "View Off", category: "alerts", tags: ["view","off"], icon: ViewOffIcon },
  { name: "password-validation", component: "Password Validation", category: "alerts", tags: ["password","validation"], icon: PasswordValidationIcon },
  { name: "scan", component: "Scan", category: "alerts", tags: ["scan"], icon: ScanIcon },
  { name: "checkmark-badge-01", component: "Checkmark Badge 01", category: "alerts", tags: ["checkmark","badge"], icon: CheckmarkBadge01Icon },
  { name: "checkmark-circle-01", component: "Checkmark Circle 01", category: "alerts", tags: ["checkmark","circle"], icon: CheckmarkCircle01Icon },
  { name: "cancel-circle-alerts", component: "Cancel Circle", category: "alerts", tags: ["cancel","circle"], icon: CancelCircleIcon },
  { name: "spam", component: "Spam", category: "alerts", tags: ["spam"], icon: SpamIcon },

  // NATURE (27)
  { name: "star", component: "Star", category: "nature", tags: ["star"], icon: StarIcon },
  { name: "heart", component: "Heart", category: "nature", tags: ["heart"], icon: HeartIcon },
  { name: "fire", component: "Fire", category: "nature", tags: ["fire"], icon: FireIcon },
  { name: "leaf-01", component: "Leaf 01", category: "nature", tags: ["leaf"], icon: Leaf01Icon },
  { name: "plant-01", component: "Plant 01", category: "nature", tags: ["plant"], icon: Plant01Icon },
  { name: "tree-01", component: "Tree 01", category: "nature", tags: ["tree"], icon: Tree01Icon },
  { name: "flower", component: "Flower", category: "nature", tags: ["flower"], icon: FlowerIcon },
  { name: "sun-01", component: "Sun 01", category: "nature", tags: ["sun"], icon: Sun01Icon },
  { name: "moon-01", component: "Moon 01", category: "nature", tags: ["moon"], icon: Moon01Icon },
  { name: "cloud-nature", component: "Cloud", category: "nature", tags: ["cloud"], icon: CloudIcon },
  { name: "cloud-rain", component: "Cloud Rain", category: "nature", tags: ["cloud","rain"], icon: CloudRainIcon },
  { name: "cloud-snow", component: "Cloud Snow", category: "nature", tags: ["cloud","snow"], icon: CloudSnowIcon },
  { name: "snow", component: "Snow", category: "nature", tags: ["snow"], icon: SnowIcon },
  { name: "water-energy", component: "Water Energy", category: "nature", tags: ["water","energy"], icon: WaterEnergyIcon },
  { name: "droplet", component: "Droplet", category: "nature", tags: ["droplet"], icon: DropletIcon },
  { name: "mountain", component: "Mountain", category: "nature", tags: ["mountain"], icon: MountainIcon },
  { name: "beach", component: "Beach", category: "nature", tags: ["beach"], icon: BeachIcon },
  { name: "earth", component: "Earth", category: "nature", tags: ["earth"], icon: EarthIcon },
  { name: "globe", component: "Globe", category: "nature", tags: ["globe"], icon: GlobeIcon },
  { name: "wind-power-01", component: "Wind Power 01", category: "nature", tags: ["wind","power"], icon: WindPower01Icon },
  { name: "rainbow", component: "Rainbow", category: "nature", tags: ["rainbow"], icon: RainbowIcon },
  { name: "eco-energy", component: "Eco Energy", category: "nature", tags: ["eco","energy"], icon: EcoEnergyIcon },
  { name: "recycle-01", component: "Recycle 01", category: "nature", tags: ["recycle"], icon: Recycle01Icon },
  { name: "apple-01", component: "Apple 01", category: "nature", tags: ["apple"], icon: Apple01Icon },
  { name: "cherry", component: "Cherry", category: "nature", tags: ["cherry"], icon: CherryIcon },
  { name: "coffee-beans", component: "Coffee Beans", category: "nature", tags: ["coffee","beans"], icon: CoffeeBeansIcon },
  { name: "wheat", component: "Wheat", category: "nature", tags: ["wheat"], icon: WheatIcon },

  // COMMERCE (28)
  { name: "shopping-cart-01", component: "Shopping Cart 01", category: "commerce", tags: ["shopping","cart"], icon: ShoppingCart01Icon },
  { name: "shopping-cart-02", component: "Shopping Cart 02", category: "commerce", tags: ["shopping","cart"], icon: ShoppingCart02Icon },
  { name: "shopping-bag-01", component: "Shopping Bag 01", category: "commerce", tags: ["shopping","bag"], icon: ShoppingBag01Icon },
  { name: "shopping-bag-02", component: "Shopping Bag 02", category: "commerce", tags: ["shopping","bag"], icon: ShoppingBag02Icon },
  { name: "store-01", component: "Store 01", category: "commerce", tags: ["store"], icon: Store01Icon },
  { name: "store-02", component: "Store 02", category: "commerce", tags: ["store"], icon: Store02Icon },
  { name: "package", component: "Package", category: "commerce", tags: ["package"], icon: PackageIcon },
  { name: "delivery-truck-01", component: "Delivery Truck 01", category: "commerce", tags: ["delivery","truck"], icon: DeliveryTruck01Icon },
  { name: "delivery-box-01", component: "Delivery Box 01", category: "commerce", tags: ["delivery","box"], icon: DeliveryBox01Icon },
  { name: "gift", component: "Gift", category: "commerce", tags: ["gift"], icon: GiftIcon },
  { name: "invoice-01-commerce", component: "Invoice 01", category: "commerce", tags: ["invoice"], icon: Invoice01Icon },
  { name: "wallet-01-commerce", component: "Wallet 01", category: "commerce", tags: ["wallet"], icon: Wallet01Icon },
  { name: "credit-card-commerce", component: "Credit Card", category: "commerce", tags: ["credit","card"], icon: CreditCardIcon },
  { name: "tag-01-commerce", component: "Tag 01", category: "commerce", tags: ["tag"], icon: Tag01Icon },
  { name: "sale-tag-01", component: "Sale Tag 01", category: "commerce", tags: ["sale","tag"], icon: SaleTag01Icon },
  { name: "qr-code", component: "Qr Code", category: "commerce", tags: ["qr","code"], icon: QrCodeIcon },
  { name: "basketball-hoop", component: "Basketball Hoop", category: "commerce", tags: ["basketball","hoop"], icon: BasketballHoopIcon },
  { name: "market-analysis", component: "Market Analysis", category: "commerce", tags: ["market","analysis"], icon: MarketAnalysisIcon },
  { name: "customer-service", component: "Customer Service", category: "commerce", tags: ["customer","service"], icon: CustomerServiceIcon },
  { name: "store-verified-01", component: "Store Verified 01", category: "commerce", tags: ["store","verified"], icon: StoreVerified01Icon },
  { name: "shipping-truck-01", component: "Shipping Truck 01", category: "commerce", tags: ["shipping","truck"], icon: ShippingTruck01Icon },
  { name: "coupon-01", component: "Coupon 01", category: "commerce", tags: ["coupon"], icon: Coupon01Icon },
  { name: "discount", component: "Discount", category: "commerce", tags: ["discount"], icon: DiscountIcon },
  { name: "cash-01-commerce", component: "Cash 01", category: "commerce", tags: ["cash"], icon: Cash01Icon },
  { name: "coins-01-commerce", component: "Coins 01", category: "commerce", tags: ["coins"], icon: Coins01Icon },
  { name: "bank-commerce", component: "Bank", category: "commerce", tags: ["bank"], icon: BankIcon },
  { name: "briefcase-01", component: "Briefcase 01", category: "commerce", tags: ["briefcase"], icon: Briefcase01Icon },
  { name: "building-02", component: "Building 02", category: "commerce", tags: ["building"], icon: Building02Icon },

] as const;

export const iconMap: Record<string, IconData> = Object.fromEntries(
  ICON_DATA.map((value) => [value.name, value]),
);

export const ICON_COLORS = [
  "#f7f8f8",
  "#ef4444",
  "#f97316",
  "#eab308",
  "#22c55e",
  "#06b6d4",
  "#3b82f6",
  "#8b5cf6",
  "#d946ef",
  "#737373",
] as const;
