name: Release

on:
  workflow_dispatch:

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: write
      pull-requests: write
      id-token: write
      packages: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v6

      - name: Install dependencies
        uses: ./.github/actions/setup

      - name: Upgrade npm for OIDC support
        run: npm install -g npm@latest

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          version: bun run version
          publish: bun run release
          commit: "chore: release"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
